/*
 * Maintenance Notification
 *
 * This service contains maintenance notification header details, item, item cause, item activity, and partner function. The information is sent in the request as a payload.    The request payload contains all information required to create or update a maintenance notification. All the information in the payload is used to create or update a maintenance notification including appropriate checks for restricted values and authorizations. Once the maintenance notification has been created, the notification number is sent in the response with the data included.    If the input in the request is not as expected when you create or update a maintenance notification, the system displays appropriate error or warning messages in the response.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace Sap.Client
{
    /// <summary>
    /// Represents configuration aspects required to interact with the API endpoints.
    /// </summary>
    public interface IApiAccessor
    {
        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        string GetBasePath();

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        ExceptionFactory ExceptionFactory { get; set; }
    }
}
