/*
 * Supplier Invoice
 *
 * This service enables you to create supplier invoices through an API call from a source system. Furthermore the service enables you to read, release, reverse and post existing supplier invoices from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.SupplierInvoice
{
    /// <summary>
    /// CancelInvoiceExportParametersD
    /// </summary>
    [DataContract(Name = "CancelInvoiceExportParameters_d")]
    public partial class CancelInvoiceExportParametersD : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CancelInvoiceExportParametersD" /> class.
        /// </summary>
        /// <param name="cancel">cancel.</param>
        public CancelInvoiceExportParametersD(CancelInvoiceExportParametersEntity cancel = default(CancelInvoiceExportParametersEntity))
        {
            this.Cancel = cancel;
        }

        /// <summary>
        /// Gets or Sets Cancel
        /// </summary>
        [DataMember(Name = "Cancel", EmitDefaultValue = false)]
        public CancelInvoiceExportParametersEntity Cancel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CancelInvoiceExportParametersD {\n");
            sb.Append("  Cancel: ").Append(Cancel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
