/*
 * Supplier Invoice
 *
 * This service enables you to create supplier invoices through an API call from a source system. Furthermore the service enables you to read, release, reverse and post existing supplier invoices from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.SupplierInvoice
{
    /// <summary>
    /// PostInvoiceExportParametersEntity
    /// </summary>
    [DataContract(Name = "API_SUPPLIERINVOICE_PROCESS_SRV.PostInvoiceExportParameters")]
    public partial class PostInvoiceExportParametersEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostInvoiceExportParametersEntity" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        public PostInvoiceExportParametersEntity(bool success = default(bool))
        {
            this.Success = success;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "Success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PostInvoiceExportParametersEntity {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
