/*
 * Supplier Invoice
 *
 * This service enables you to create supplier invoices through an API call from a source system. Furthermore the service enables you to read, release, reverse and post existing supplier invoices from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.SupplierInvoice
{
    /// <summary>
    /// SupplierInvoiceSeldPurgDocumentEntity
    /// </summary>
    [DataContract(Name = "API_SUPPLIERINVOICE_PROCESS_SRV.A_SuplrInvcSeldPurgDocumentType")]
    public partial class SupplierInvoiceSeldPurgDocumentEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupplierInvoiceSeldPurgDocumentEntity" /> class.
        /// </summary>
        /// <param name="supplierInvoice">Document Number of an Accounting Document.</param>
        /// <param name="fiscalYear">fiscalYear.</param>
        /// <param name="purchaseOrder">Purchasing Document Number.</param>
        /// <param name="purchaseOrderItem">Item Number of Purchasing Document.</param>
        public SupplierInvoiceSeldPurgDocumentEntity(string supplierInvoice = default(string), string fiscalYear = default(string), string purchaseOrder = default(string), string purchaseOrderItem = default(string))
        {
            this.SupplierInvoice = supplierInvoice;
            this.FiscalYear = fiscalYear;
            this.PurchaseOrder = purchaseOrder;
            this.PurchaseOrderItem = purchaseOrderItem;
        }

        /// <summary>
        /// Document Number of an Accounting Document
        /// </summary>
        /// <value>Document Number of an Accounting Document</value>
        [DataMember(Name = "SupplierInvoice", EmitDefaultValue = false)]
        public string SupplierInvoice { get; set; }

        /// <summary>
        /// Gets or Sets FiscalYear
        /// </summary>
        [DataMember(Name = "FiscalYear", EmitDefaultValue = false)]
        public string FiscalYear { get; set; }

        /// <summary>
        /// Purchasing Document Number
        /// </summary>
        /// <value>Purchasing Document Number</value>
        [DataMember(Name = "PurchaseOrder", EmitDefaultValue = false)]
        public string PurchaseOrder { get; set; }

        /// <summary>
        /// Item Number of Purchasing Document
        /// </summary>
        /// <value>Item Number of Purchasing Document</value>
        [DataMember(Name = "PurchaseOrderItem", EmitDefaultValue = false)]
        public string PurchaseOrderItem { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupplierInvoiceSeldPurgDocumentEntity {\n");
            sb.Append("  SupplierInvoice: ").Append(SupplierInvoice).Append("\n");
            sb.Append("  FiscalYear: ").Append(FiscalYear).Append("\n");
            sb.Append("  PurchaseOrder: ").Append(PurchaseOrder).Append("\n");
            sb.Append("  PurchaseOrderItem: ").Append(PurchaseOrderItem).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SupplierInvoice (string) maxLength
            if (this.SupplierInvoice != null && this.SupplierInvoice.Length > 10)
            {
                yield return new ValidationResult("Invalid value for SupplierInvoice, length must be less than 10.", new [] { "SupplierInvoice" });
            }

            // FiscalYear (string) maxLength
            if (this.FiscalYear != null && this.FiscalYear.Length > 4)
            {
                yield return new ValidationResult("Invalid value for FiscalYear, length must be less than 4.", new [] { "FiscalYear" });
            }

            // PurchaseOrder (string) maxLength
            if (this.PurchaseOrder != null && this.PurchaseOrder.Length > 10)
            {
                yield return new ValidationResult("Invalid value for PurchaseOrder, length must be less than 10.", new [] { "PurchaseOrder" });
            }

            // PurchaseOrderItem (string) maxLength
            if (this.PurchaseOrderItem != null && this.PurchaseOrderItem.Length > 5)
            {
                yield return new ValidationResult("Invalid value for PurchaseOrderItem, length must be less than 5.", new [] { "PurchaseOrderItem" });
            }

            yield break;
        }
    }

}
