/*
 * Supplier Invoice
 *
 * This service enables you to create supplier invoices through an API call from a source system. Furthermore the service enables you to read, release, reverse and post existing supplier invoices from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.SupplierInvoice
{
    /// <summary>
    /// SupplierInvoiceNFDocumentCreate
    /// </summary>
    [DataContract(Name = "API_SUPPLIERINVOICE_PROCESS_SRV.A_BR_SupplierInvoiceNFDocumentType-create")]
    public partial class SupplierInvoiceNFDocumentCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupplierInvoiceNFDocumentCreate" /> class.
        /// </summary>
        /// <param name="bRNFType">bRNFType.</param>
        /// <param name="bRNFSNumber">Service NF-e Number.</param>
        /// <param name="bRNFSVerificationCode">bRNFSVerificationCode.</param>
        /// <param name="bRNFAuthznProtocolNumber">bRNFAuthznProtocolNumber.</param>
        /// <param name="bRNFAuthznProtocolNumber16">bRNFAuthznProtocolNumber16.</param>
        /// <param name="bRNFAuthenticationDate">bRNFAuthenticationDate.</param>
        /// <param name="bRNFAuthenticationTime">bRNFAuthenticationTime.</param>
        /// <param name="bRNFeRandomNumber">bRNFeRandomNumber.</param>
        /// <param name="issuingType">issuingType.</param>
        public SupplierInvoiceNFDocumentCreate(string bRNFType = default(string), string bRNFSNumber = default(string), string bRNFSVerificationCode = default(string), string bRNFAuthznProtocolNumber = default(string), string bRNFAuthznProtocolNumber16 = default(string), string bRNFAuthenticationDate = default(string), string bRNFAuthenticationTime = default(string), string bRNFeRandomNumber = default(string), string issuingType = default(string))
        {
            this.BRNFType = bRNFType;
            this.BRNFSNumber = bRNFSNumber;
            this.BRNFSVerificationCode = bRNFSVerificationCode;
            this.BRNFAuthznProtocolNumber = bRNFAuthznProtocolNumber;
            this.BRNFAuthznProtocolNumber16 = bRNFAuthznProtocolNumber16;
            this.BRNFAuthenticationDate = bRNFAuthenticationDate;
            this.BRNFAuthenticationTime = bRNFAuthenticationTime;
            this.BRNFeRandomNumber = bRNFeRandomNumber;
            this.IssuingType = issuingType;
        }

        /// <summary>
        /// Gets or Sets BRNFType
        /// </summary>
        [DataMember(Name = "BR_NFType", EmitDefaultValue = true)]
        public string BRNFType { get; set; }

        /// <summary>
        /// Service NF-e Number
        /// </summary>
        /// <value>Service NF-e Number</value>
        [DataMember(Name = "BR_NFSNumber", EmitDefaultValue = true)]
        public string BRNFSNumber { get; set; }

        /// <summary>
        /// Gets or Sets BRNFSVerificationCode
        /// </summary>
        [DataMember(Name = "BR_NFSVerificationCode", EmitDefaultValue = true)]
        public string BRNFSVerificationCode { get; set; }

        /// <summary>
        /// Gets or Sets BRNFAuthznProtocolNumber
        /// </summary>
        [DataMember(Name = "BR_NFAuthznProtocolNumber", EmitDefaultValue = true)]
        public string BRNFAuthznProtocolNumber { get; set; }

        /// <summary>
        /// Gets or Sets BRNFAuthznProtocolNumber16
        /// </summary>
        [DataMember(Name = "BR_NFAuthznProtocolNumber16", EmitDefaultValue = true)]
        public string BRNFAuthznProtocolNumber16 { get; set; }

        /// <summary>
        /// Gets or Sets BRNFAuthenticationDate
        /// </summary>
        /// <example>/Date(1492041600000)/</example>
        [DataMember(Name = "BR_NFAuthenticationDate", EmitDefaultValue = true)]
        public string BRNFAuthenticationDate { get; set; }

        /// <summary>
        /// Gets or Sets BRNFAuthenticationTime
        /// </summary>
        /// <example>PT15H51M04S</example>
        [DataMember(Name = "BR_NFAuthenticationTime", EmitDefaultValue = true)]
        public string BRNFAuthenticationTime { get; set; }

        /// <summary>
        /// Gets or Sets BRNFeRandomNumber
        /// </summary>
        [DataMember(Name = "BR_NFeRandomNumber", EmitDefaultValue = true)]
        public string BRNFeRandomNumber { get; set; }

        /// <summary>
        /// Gets or Sets IssuingType
        /// </summary>
        [DataMember(Name = "IssuingType", EmitDefaultValue = true)]
        public string IssuingType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupplierInvoiceNFDocumentCreate {\n");
            sb.Append("  BRNFType: ").Append(BRNFType).Append("\n");
            sb.Append("  BRNFSNumber: ").Append(BRNFSNumber).Append("\n");
            sb.Append("  BRNFSVerificationCode: ").Append(BRNFSVerificationCode).Append("\n");
            sb.Append("  BRNFAuthznProtocolNumber: ").Append(BRNFAuthznProtocolNumber).Append("\n");
            sb.Append("  BRNFAuthznProtocolNumber16: ").Append(BRNFAuthznProtocolNumber16).Append("\n");
            sb.Append("  BRNFAuthenticationDate: ").Append(BRNFAuthenticationDate).Append("\n");
            sb.Append("  BRNFAuthenticationTime: ").Append(BRNFAuthenticationTime).Append("\n");
            sb.Append("  BRNFeRandomNumber: ").Append(BRNFeRandomNumber).Append("\n");
            sb.Append("  IssuingType: ").Append(IssuingType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // BRNFType (string) maxLength
            if (this.BRNFType != null && this.BRNFType.Length > 2)
            {
                yield return new ValidationResult("Invalid value for BRNFType, length must be less than 2.", new [] { "BRNFType" });
            }

            // BRNFSNumber (string) maxLength
            if (this.BRNFSNumber != null && this.BRNFSNumber.Length > 20)
            {
                yield return new ValidationResult("Invalid value for BRNFSNumber, length must be less than 20.", new [] { "BRNFSNumber" });
            }

            // BRNFSVerificationCode (string) maxLength
            if (this.BRNFSVerificationCode != null && this.BRNFSVerificationCode.Length > 20)
            {
                yield return new ValidationResult("Invalid value for BRNFSVerificationCode, length must be less than 20.", new [] { "BRNFSVerificationCode" });
            }

            // BRNFAuthznProtocolNumber (string) maxLength
            if (this.BRNFAuthznProtocolNumber != null && this.BRNFAuthznProtocolNumber.Length > 15)
            {
                yield return new ValidationResult("Invalid value for BRNFAuthznProtocolNumber, length must be less than 15.", new [] { "BRNFAuthznProtocolNumber" });
            }

            // BRNFAuthznProtocolNumber16 (string) maxLength
            if (this.BRNFAuthznProtocolNumber16 != null && this.BRNFAuthznProtocolNumber16.Length > 16)
            {
                yield return new ValidationResult("Invalid value for BRNFAuthznProtocolNumber16, length must be less than 16.", new [] { "BRNFAuthznProtocolNumber16" });
            }

            // BRNFeRandomNumber (string) maxLength
            if (this.BRNFeRandomNumber != null && this.BRNFeRandomNumber.Length > 9)
            {
                yield return new ValidationResult("Invalid value for BRNFeRandomNumber, length must be less than 9.", new [] { "BRNFeRandomNumber" });
            }

            // IssuingType (string) maxLength
            if (this.IssuingType != null && this.IssuingType.Length > 1)
            {
                yield return new ValidationResult("Invalid value for IssuingType, length must be less than 1.", new [] { "IssuingType" });
            }

            yield break;
        }
    }

}
