/*
 * Supplier Invoice
 *
 * This service enables you to create supplier invoices through an API call from a source system. Furthermore the service enables you to read, release, reverse and post existing supplier invoices from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Sap.Model.SupplierInvoice
{
    /// <summary>
    /// SupplierInvoiceSeldSrvcEntrShtLeanCreate
    /// </summary>
    [DataContract(Name = "API_SUPPLIERINVOICE_PROCESS_SRV.A_SuplrInvcSeldSrvcEntrShtLeanType-create")]
    public partial class SupplierInvoiceSeldSrvcEntrShtLeanCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SupplierInvoiceSeldSrvcEntrShtLeanCreate" /> class.
        /// </summary>
        [JsonConstructor]
        protected SupplierInvoiceSeldSrvcEntrShtLeanCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SupplierInvoiceSeldSrvcEntrShtLeanCreate" /> class.
        /// </summary>
        /// <param name="serviceEntrySheet">serviceEntrySheet (required).</param>
        /// <param name="serviceEntrySheetItem">Item Number of Service Entry Sheet (required).</param>
        public SupplierInvoiceSeldSrvcEntrShtLeanCreate(string serviceEntrySheet = default(string), string serviceEntrySheetItem = default(string))
        {
            // to ensure "serviceEntrySheet" is required (not null)
            if (serviceEntrySheet == null)
            {
                throw new ArgumentNullException("serviceEntrySheet is a required property for SupplierInvoiceSeldSrvcEntrShtLeanCreate and cannot be null");
            }
            this.ServiceEntrySheet = serviceEntrySheet;
            // to ensure "serviceEntrySheetItem" is required (not null)
            if (serviceEntrySheetItem == null)
            {
                throw new ArgumentNullException("serviceEntrySheetItem is a required property for SupplierInvoiceSeldSrvcEntrShtLeanCreate and cannot be null");
            }
            this.ServiceEntrySheetItem = serviceEntrySheetItem;
        }

        /// <summary>
        /// Gets or Sets ServiceEntrySheet
        /// </summary>
        [DataMember(Name = "ServiceEntrySheet", IsRequired = true, EmitDefaultValue = true)]
        public string ServiceEntrySheet { get; set; }

        /// <summary>
        /// Item Number of Service Entry Sheet
        /// </summary>
        /// <value>Item Number of Service Entry Sheet</value>
        [DataMember(Name = "ServiceEntrySheetItem", IsRequired = true, EmitDefaultValue = true)]
        public string ServiceEntrySheetItem { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SupplierInvoiceSeldSrvcEntrShtLeanCreate {\n");
            sb.Append("  ServiceEntrySheet: ").Append(ServiceEntrySheet).Append("\n");
            sb.Append("  ServiceEntrySheetItem: ").Append(ServiceEntrySheetItem).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ServiceEntrySheet (string) maxLength
            if (this.ServiceEntrySheet != null && this.ServiceEntrySheet.Length > 10)
            {
                yield return new ValidationResult("Invalid value for ServiceEntrySheet, length must be less than 10.", new [] { "ServiceEntrySheet" });
            }

            // ServiceEntrySheetItem (string) maxLength
            if (this.ServiceEntrySheetItem != null && this.ServiceEntrySheetItem.Length > 5)
            {
                yield return new ValidationResult("Invalid value for ServiceEntrySheetItem, length must be less than 5.", new [] { "ServiceEntrySheetItem" });
            }

            yield break;
        }
    }

}
