/*
 * Maintenance Order
 *
 * This service enables you to create, read, updated and delete maintenance order data. It contains order header, operation, component, object list item, operation relationship, long text and settlement rule nodes. The service is based on the OData V2 protocol, and can be consumed in external systems, Fiori applications and on other user interfaces.    If there are any issues when retrieving the maintenance order data, the system displays appropriate warning or error messages in the response.
 *
 * The version of the OpenAPI document: 2.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sap.Client.OpenAPIDateConverter;

namespace Sap.Model.MaintenanceOrder
{
    /// <summary>
    /// DummyFunctionImportResult1D
    /// </summary>
    [DataContract(Name = "DummyFunctionImportResult_1_d")]
    public partial class DummyFunctionImportResult1D : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DummyFunctionImportResult1D" /> class.
        /// </summary>
        /// <param name="assignMaintNotificationToOrder">assignMaintNotificationToOrder.</param>
        public DummyFunctionImportResult1D(DummyFunctionImportResultEntity assignMaintNotificationToOrder = default(DummyFunctionImportResultEntity))
        {
            this.AssignMaintNotificationToOrder = assignMaintNotificationToOrder;
        }

        /// <summary>
        /// Gets or Sets AssignMaintNotificationToOrder
        /// </summary>
        [DataMember(Name = "AssignMaintNotificationToOrder", EmitDefaultValue = false)]
        public DummyFunctionImportResultEntity AssignMaintNotificationToOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DummyFunctionImportResult1D {\n");
            sb.Append("  AssignMaintNotificationToOrder: ").Append(AssignMaintNotificationToOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}

