/*
 * Maintenance Order
 *
 * This service enables you to create, read, updated and delete maintenance order data. It contains order header, operation, component, object list item, operation relationship, long text and settlement rule nodes. The service is based on the OData V2 protocol, and can be consumed in external systems, Fiori applications and on other user interfaces.    If there are any issues when retrieving the maintenance order data, the system displays appropriate warning or error messages in the response.
 *
 * The version of the OpenAPI document: 2.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sap.Client.OpenAPIDateConverter;

namespace Sap.Model.MaintenanceOrder
{
    /// <summary>
    /// MaintenanceOrderPhaseControlEntity
    /// </summary>
    [DataContract(Name = "cds_api_maintenanceorder_2.MaintnanceOrderPhaseControl_Type")]
    public partial class MaintenanceOrderPhaseControlEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceOrderPhaseControlEntity" /> class.
        /// </summary>
        /// <param name="maintenanceOrder">Order Number.</param>
        /// <param name="maintenancePhaseControl">Phase Control Code.</param>
        /// <param name="maintenancePhaseControlName">Phase Control Code.</param>
        /// <param name="maintenancePhaseControlText">Description of the Phase Control Code.</param>
        /// <param name="maintPhseCtrlIsSetAutomly">Phase Control Code: Set Automatically.</param>
        /// <param name="maintPhaseControlAuthorityCode">Authorization Key for Phase Control Code.</param>
        /// <param name="maintProcgPhseCtrlActvtnCode">maintProcgPhseCtrlActvtnCode.</param>
        /// <param name="maintProcgPhseCtrlActvtnDesc">Short Text for Fixed Values.</param>
        /// <param name="eAMProcessPhaseCode">eAMProcessPhaseCode.</param>
        /// <param name="eAMProcessSubPhaseCode">eAMProcessSubPhaseCode.</param>
        /// <param name="maintObjPhseCtrlStatusIsActive">maintObjPhseCtrlStatusIsActive.</param>
        /// <param name="statusObject">statusObject.</param>
        /// <param name="maintObjPhaseCtrlCodeSetBy">Business Object Blocker Code Set By User ID.</param>
        /// <param name="maintObjPhseCtrlCodeSetDteTime">Business Object Phase Control Code Activated On.</param>
        /// <param name="maintObjPhaseCtrlCodeResetBy">Business Object Blocker Code Resolved By User ID.</param>
        /// <param name="maintObjPhseCtrlCodeRsetDteTme">Business Object Phase Control Code Deactivated On.</param>
        /// <param name="toMaintenanceOrder">toMaintenanceOrder.</param>
        public MaintenanceOrderPhaseControlEntity(string maintenanceOrder = default(string), string maintenancePhaseControl = default(string), string maintenancePhaseControlName = default(string), string maintenancePhaseControlText = default(string), bool? maintPhseCtrlIsSetAutomly = default(bool?), string maintPhaseControlAuthorityCode = default(string), string maintProcgPhseCtrlActvtnCode = default(string), string maintProcgPhseCtrlActvtnDesc = default(string), string eAMProcessPhaseCode = default(string), string eAMProcessSubPhaseCode = default(string), bool? maintObjPhseCtrlStatusIsActive = default(bool?), string statusObject = default(string), string maintObjPhaseCtrlCodeSetBy = default(string), string maintObjPhseCtrlCodeSetDteTime = default(string), string maintObjPhaseCtrlCodeResetBy = default(string), string maintObjPhseCtrlCodeRsetDteTme = default(string), MaintenanceOrderEntity toMaintenanceOrder = default(MaintenanceOrderEntity))
        {
            this.MaintenanceOrder = maintenanceOrder;
            this.MaintenancePhaseControl = maintenancePhaseControl;
            this.MaintenancePhaseControlName = maintenancePhaseControlName;
            this.MaintenancePhaseControlText = maintenancePhaseControlText;
            this.MaintPhseCtrlIsSetAutomly = maintPhseCtrlIsSetAutomly;
            this.MaintPhaseControlAuthorityCode = maintPhaseControlAuthorityCode;
            this.MaintProcgPhseCtrlActvtnCode = maintProcgPhseCtrlActvtnCode;
            this.MaintProcgPhseCtrlActvtnDesc = maintProcgPhseCtrlActvtnDesc;
            this.EAMProcessPhaseCode = eAMProcessPhaseCode;
            this.EAMProcessSubPhaseCode = eAMProcessSubPhaseCode;
            this.MaintObjPhseCtrlStatusIsActive = maintObjPhseCtrlStatusIsActive;
            this.StatusObject = statusObject;
            this.MaintObjPhaseCtrlCodeSetBy = maintObjPhaseCtrlCodeSetBy;
            this.MaintObjPhseCtrlCodeSetDteTime = maintObjPhseCtrlCodeSetDteTime;
            this.MaintObjPhaseCtrlCodeResetBy = maintObjPhaseCtrlCodeResetBy;
            this.MaintObjPhseCtrlCodeRsetDteTme = maintObjPhseCtrlCodeRsetDteTme;
            this.ToMaintenanceOrder = toMaintenanceOrder;
        }

        /// <summary>
        /// Order Number
        /// </summary>
        /// <value>Order Number</value>
        [DataMember(Name = "MaintenanceOrder", EmitDefaultValue = false)]
        public string MaintenanceOrder { get; set; }

        /// <summary>
        /// Phase Control Code
        /// </summary>
        /// <value>Phase Control Code</value>
        [DataMember(Name = "MaintenancePhaseControl", EmitDefaultValue = false)]
        public string MaintenancePhaseControl { get; set; }

        /// <summary>
        /// Phase Control Code
        /// </summary>
        /// <value>Phase Control Code</value>
        [DataMember(Name = "MaintenancePhaseControlName", EmitDefaultValue = true)]
        public string MaintenancePhaseControlName { get; set; }

        /// <summary>
        /// Description of the Phase Control Code
        /// </summary>
        /// <value>Description of the Phase Control Code</value>
        [DataMember(Name = "MaintenancePhaseControlText", EmitDefaultValue = true)]
        public string MaintenancePhaseControlText { get; set; }

        /// <summary>
        /// Phase Control Code: Set Automatically
        /// </summary>
        /// <value>Phase Control Code: Set Automatically</value>
        [DataMember(Name = "MaintPhseCtrlIsSetAutomly", EmitDefaultValue = true)]
        public bool? MaintPhseCtrlIsSetAutomly { get; set; }

        /// <summary>
        /// Authorization Key for Phase Control Code
        /// </summary>
        /// <value>Authorization Key for Phase Control Code</value>
        [DataMember(Name = "MaintPhaseControlAuthorityCode", EmitDefaultValue = true)]
        public string MaintPhaseControlAuthorityCode { get; set; }

        /// <summary>
        /// Gets or Sets MaintProcgPhseCtrlActvtnCode
        /// </summary>
        [DataMember(Name = "MaintProcgPhseCtrlActvtnCode", EmitDefaultValue = true)]
        public string MaintProcgPhseCtrlActvtnCode { get; set; }

        /// <summary>
        /// Short Text for Fixed Values
        /// </summary>
        /// <value>Short Text for Fixed Values</value>
        [DataMember(Name = "MaintProcgPhseCtrlActvtnDesc", EmitDefaultValue = true)]
        public string MaintProcgPhseCtrlActvtnDesc { get; set; }

        /// <summary>
        /// Gets or Sets EAMProcessPhaseCode
        /// </summary>
        [DataMember(Name = "EAMProcessPhaseCode", EmitDefaultValue = true)]
        public string EAMProcessPhaseCode { get; set; }

        /// <summary>
        /// Gets or Sets EAMProcessSubPhaseCode
        /// </summary>
        [DataMember(Name = "EAMProcessSubPhaseCode", EmitDefaultValue = true)]
        public string EAMProcessSubPhaseCode { get; set; }

        /// <summary>
        /// Gets or Sets MaintObjPhseCtrlStatusIsActive
        /// </summary>
        [DataMember(Name = "MaintObjPhseCtrlStatusIsActive", EmitDefaultValue = true)]
        public bool? MaintObjPhseCtrlStatusIsActive { get; set; }

        /// <summary>
        /// Gets or Sets StatusObject
        /// </summary>
        [DataMember(Name = "StatusObject", EmitDefaultValue = true)]
        public string StatusObject { get; set; }

        /// <summary>
        /// Business Object Blocker Code Set By User ID
        /// </summary>
        /// <value>Business Object Blocker Code Set By User ID</value>
        [DataMember(Name = "MaintObjPhaseCtrlCodeSetBy", EmitDefaultValue = true)]
        public string MaintObjPhaseCtrlCodeSetBy { get; set; }

        /// <summary>
        /// Business Object Phase Control Code Activated On
        /// </summary>
        /// <value>Business Object Phase Control Code Activated On</value>
        /// <example>/Date(1492098664000)/</example>
        [DataMember(Name = "MaintObjPhseCtrlCodeSetDteTime", EmitDefaultValue = true)]
        public string MaintObjPhseCtrlCodeSetDteTime { get; set; }

        /// <summary>
        /// Business Object Blocker Code Resolved By User ID
        /// </summary>
        /// <value>Business Object Blocker Code Resolved By User ID</value>
        [DataMember(Name = "MaintObjPhaseCtrlCodeResetBy", EmitDefaultValue = true)]
        public string MaintObjPhaseCtrlCodeResetBy { get; set; }

        /// <summary>
        /// Business Object Phase Control Code Deactivated On
        /// </summary>
        /// <value>Business Object Phase Control Code Deactivated On</value>
        /// <example>/Date(1492098664000)/</example>
        [DataMember(Name = "MaintObjPhseCtrlCodeRsetDteTme", EmitDefaultValue = true)]
        public string MaintObjPhseCtrlCodeRsetDteTme { get; set; }

        /// <summary>
        /// Gets or Sets ToMaintenanceOrder
        /// </summary>
        [DataMember(Name = "to_MaintenanceOrder", EmitDefaultValue = false)]
        public MaintenanceOrderEntity ToMaintenanceOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintenanceOrderPhaseControlEntity {\n");
            sb.Append("  MaintenanceOrder: ").Append(MaintenanceOrder).Append("\n");
            sb.Append("  MaintenancePhaseControl: ").Append(MaintenancePhaseControl).Append("\n");
            sb.Append("  MaintenancePhaseControlName: ").Append(MaintenancePhaseControlName).Append("\n");
            sb.Append("  MaintenancePhaseControlText: ").Append(MaintenancePhaseControlText).Append("\n");
            sb.Append("  MaintPhseCtrlIsSetAutomly: ").Append(MaintPhseCtrlIsSetAutomly).Append("\n");
            sb.Append("  MaintPhaseControlAuthorityCode: ").Append(MaintPhaseControlAuthorityCode).Append("\n");
            sb.Append("  MaintProcgPhseCtrlActvtnCode: ").Append(MaintProcgPhseCtrlActvtnCode).Append("\n");
            sb.Append("  MaintProcgPhseCtrlActvtnDesc: ").Append(MaintProcgPhseCtrlActvtnDesc).Append("\n");
            sb.Append("  EAMProcessPhaseCode: ").Append(EAMProcessPhaseCode).Append("\n");
            sb.Append("  EAMProcessSubPhaseCode: ").Append(EAMProcessSubPhaseCode).Append("\n");
            sb.Append("  MaintObjPhseCtrlStatusIsActive: ").Append(MaintObjPhseCtrlStatusIsActive).Append("\n");
            sb.Append("  StatusObject: ").Append(StatusObject).Append("\n");
            sb.Append("  MaintObjPhaseCtrlCodeSetBy: ").Append(MaintObjPhaseCtrlCodeSetBy).Append("\n");
            sb.Append("  MaintObjPhseCtrlCodeSetDteTime: ").Append(MaintObjPhseCtrlCodeSetDteTime).Append("\n");
            sb.Append("  MaintObjPhaseCtrlCodeResetBy: ").Append(MaintObjPhaseCtrlCodeResetBy).Append("\n");
            sb.Append("  MaintObjPhseCtrlCodeRsetDteTme: ").Append(MaintObjPhseCtrlCodeRsetDteTme).Append("\n");
            sb.Append("  ToMaintenanceOrder: ").Append(ToMaintenanceOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaintenanceOrder (string) maxLength
            if (this.MaintenanceOrder != null && this.MaintenanceOrder.Length > 12)
            {
                yield return new ValidationResult("Invalid value for MaintenanceOrder, length must be less than 12.", new [] { "MaintenanceOrder" });
            }

            // MaintenancePhaseControl (string) maxLength
            if (this.MaintenancePhaseControl != null && this.MaintenancePhaseControl.Length > 4)
            {
                yield return new ValidationResult("Invalid value for MaintenancePhaseControl, length must be less than 4.", new [] { "MaintenancePhaseControl" });
            }

            // MaintenancePhaseControlName (string) maxLength
            if (this.MaintenancePhaseControlName != null && this.MaintenancePhaseControlName.Length > 4)
            {
                yield return new ValidationResult("Invalid value for MaintenancePhaseControlName, length must be less than 4.", new [] { "MaintenancePhaseControlName" });
            }

            // MaintenancePhaseControlText (string) maxLength
            if (this.MaintenancePhaseControlText != null && this.MaintenancePhaseControlText.Length > 30)
            {
                yield return new ValidationResult("Invalid value for MaintenancePhaseControlText, length must be less than 30.", new [] { "MaintenancePhaseControlText" });
            }

            // MaintPhaseControlAuthorityCode (string) maxLength
            if (this.MaintPhaseControlAuthorityCode != null && this.MaintPhaseControlAuthorityCode.Length > 8)
            {
                yield return new ValidationResult("Invalid value for MaintPhaseControlAuthorityCode, length must be less than 8.", new [] { "MaintPhaseControlAuthorityCode" });
            }

            // MaintProcgPhseCtrlActvtnCode (string) maxLength
            if (this.MaintProcgPhseCtrlActvtnCode != null && this.MaintProcgPhseCtrlActvtnCode.Length > 2)
            {
                yield return new ValidationResult("Invalid value for MaintProcgPhseCtrlActvtnCode, length must be less than 2.", new [] { "MaintProcgPhseCtrlActvtnCode" });
            }

            // MaintProcgPhseCtrlActvtnDesc (string) maxLength
            if (this.MaintProcgPhseCtrlActvtnDesc != null && this.MaintProcgPhseCtrlActvtnDesc.Length > 60)
            {
                yield return new ValidationResult("Invalid value for MaintProcgPhseCtrlActvtnDesc, length must be less than 60.", new [] { "MaintProcgPhseCtrlActvtnDesc" });
            }

            // EAMProcessPhaseCode (string) maxLength
            if (this.EAMProcessPhaseCode != null && this.EAMProcessPhaseCode.Length > 2)
            {
                yield return new ValidationResult("Invalid value for EAMProcessPhaseCode, length must be less than 2.", new [] { "EAMProcessPhaseCode" });
            }

            // EAMProcessSubPhaseCode (string) maxLength
            if (this.EAMProcessSubPhaseCode != null && this.EAMProcessSubPhaseCode.Length > 4)
            {
                yield return new ValidationResult("Invalid value for EAMProcessSubPhaseCode, length must be less than 4.", new [] { "EAMProcessSubPhaseCode" });
            }

            // StatusObject (string) maxLength
            if (this.StatusObject != null && this.StatusObject.Length > 22)
            {
                yield return new ValidationResult("Invalid value for StatusObject, length must be less than 22.", new [] { "StatusObject" });
            }

            // MaintObjPhaseCtrlCodeSetBy (string) maxLength
            if (this.MaintObjPhaseCtrlCodeSetBy != null && this.MaintObjPhaseCtrlCodeSetBy.Length > 12)
            {
                yield return new ValidationResult("Invalid value for MaintObjPhaseCtrlCodeSetBy, length must be less than 12.", new [] { "MaintObjPhaseCtrlCodeSetBy" });
            }

            // MaintObjPhaseCtrlCodeResetBy (string) maxLength
            if (this.MaintObjPhaseCtrlCodeResetBy != null && this.MaintObjPhaseCtrlCodeResetBy.Length > 12)
            {
                yield return new ValidationResult("Invalid value for MaintObjPhaseCtrlCodeResetBy, length must be less than 12.", new [] { "MaintObjPhaseCtrlCodeResetBy" });
            }

            yield break;
        }
    }

}

