/*
 * Maintenance Order
 *
 * This service enables you to create, read, updated and delete maintenance order data. It contains order header, operation, component, object list item, operation relationship, long text and settlement rule nodes. The service is based on the OData V2 protocol, and can be consumed in external systems, Fiori applications and on other user interfaces.    If there are any issues when retrieving the maintenance order data, the system displays appropriate warning or error messages in the response.
 *
 * The version of the OpenAPI document: 2.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sap.Client.OpenAPIDateConverter;

namespace Sap.Model.MaintenanceOrder
{
    /// <summary>
    /// MaintenanceOrderPartnerCreate
    /// </summary>
    [DataContract(Name = "cds_api_maintenanceorder_2.MaintenanceOrderPartner_Type-create")]
    public partial class MaintenanceOrderPartnerCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceOrderPartnerCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MaintenanceOrderPartnerCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceOrderPartnerCreate" /> class.
        /// </summary>
        /// <param name="partnerFunction">partnerFunction (required).</param>
        /// <param name="maintenanceOrderPartner">maintenanceOrderPartner (required).</param>
        /// <param name="toMaintenanceOrder">toMaintenanceOrder.</param>
        public MaintenanceOrderPartnerCreate(string partnerFunction = default(string), string maintenanceOrderPartner = default(string), MaintenanceOrderCreate toMaintenanceOrder = default(MaintenanceOrderCreate))
        {
            // to ensure "partnerFunction" is required (not null)
            if (partnerFunction == null)
            {
                throw new ArgumentNullException("partnerFunction is a required property for MaintenanceOrderPartnerCreate and cannot be null");
            }
            this.PartnerFunction = partnerFunction;
            // to ensure "maintenanceOrderPartner" is required (not null)
            if (maintenanceOrderPartner == null)
            {
                throw new ArgumentNullException("maintenanceOrderPartner is a required property for MaintenanceOrderPartnerCreate and cannot be null");
            }
            this.MaintenanceOrderPartner = maintenanceOrderPartner;
            this.ToMaintenanceOrder = toMaintenanceOrder;
        }

        /// <summary>
        /// Gets or Sets PartnerFunction
        /// </summary>
        [DataMember(Name = "PartnerFunction", IsRequired = true, EmitDefaultValue = true)]
        public string PartnerFunction { get; set; }

        /// <summary>
        /// Gets or Sets MaintenanceOrderPartner
        /// </summary>
        [DataMember(Name = "MaintenanceOrderPartner", IsRequired = true, EmitDefaultValue = true)]
        public string MaintenanceOrderPartner { get; set; }

        /// <summary>
        /// Gets or Sets ToMaintenanceOrder
        /// </summary>
        [DataMember(Name = "to_MaintenanceOrder", EmitDefaultValue = false)]
        public MaintenanceOrderCreate ToMaintenanceOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintenanceOrderPartnerCreate {\n");
            sb.Append("  PartnerFunction: ").Append(PartnerFunction).Append("\n");
            sb.Append("  MaintenanceOrderPartner: ").Append(MaintenanceOrderPartner).Append("\n");
            sb.Append("  ToMaintenanceOrder: ").Append(ToMaintenanceOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PartnerFunction (string) maxLength
            if (this.PartnerFunction != null && this.PartnerFunction.Length > 2)
            {
                yield return new ValidationResult("Invalid value for PartnerFunction, length must be less than 2.", new [] { "PartnerFunction" });
            }

            // MaintenanceOrderPartner (string) maxLength
            if (this.MaintenanceOrderPartner != null && this.MaintenanceOrderPartner.Length > 12)
            {
                yield return new ValidationResult("Invalid value for MaintenanceOrderPartner, length must be less than 12.", new [] { "MaintenanceOrderPartner" });
            }

            yield break;
        }
    }

}

