/*
 * Maintenance Order
 *
 * This service enables you to create, read, updated and delete maintenance order data. It contains order header, operation, component, object list item, operation relationship, long text and settlement rule nodes. The service is based on the OData V2 protocol, and can be consumed in external systems, Fiori applications and on other user interfaces.    If there are any issues when retrieving the maintenance order data, the system displays appropriate warning or error messages in the response.
 *
 * The version of the OpenAPI document: 2.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sap.Client.OpenAPIDateConverter;

namespace Sap.Model.MaintenanceOrder
{
    /// <summary>
    /// MaintenanceOrderOperationComponentLongTextCreate
    /// </summary>
    [DataContract(Name = "cds_api_maintenanceorder_2.MaintOrderOpCompLongText_Type-create")]
    public partial class MaintenanceOrderOperationComponentLongTextCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceOrderOperationComponentLongTextCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MaintenanceOrderOperationComponentLongTextCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceOrderOperationComponentLongTextCreate" /> class.
        /// </summary>
        /// <param name="textObjectType">textObjectType (required).</param>
        /// <param name="language">language (required).</param>
        /// <param name="orderComponentLongText">orderComponentLongText.</param>
        /// <param name="toMaintenanceOrder">toMaintenanceOrder.</param>
        /// <param name="toMaintenanceOrderComponent">toMaintenanceOrderComponent.</param>
        public MaintenanceOrderOperationComponentLongTextCreate(string textObjectType = default(string), string language = default(string), string orderComponentLongText = default(string), MaintenanceOrderCreate toMaintenanceOrder = default(MaintenanceOrderCreate), MaintenanceOrderOperationComponentEntityCreate toMaintenanceOrderComponent = default(MaintenanceOrderOperationComponentEntityCreate))
        {
            // to ensure "textObjectType" is required (not null)
            if (textObjectType == null)
            {
                throw new ArgumentNullException("textObjectType is a required property for MaintenanceOrderOperationComponentLongTextCreate and cannot be null");
            }
            this.TextObjectType = textObjectType;
            // to ensure "language" is required (not null)
            if (language == null)
            {
                throw new ArgumentNullException("language is a required property for MaintenanceOrderOperationComponentLongTextCreate and cannot be null");
            }
            this.Language = language;
            this.OrderComponentLongText = orderComponentLongText;
            this.ToMaintenanceOrder = toMaintenanceOrder;
            this.ToMaintenanceOrderComponent = toMaintenanceOrderComponent;
        }

        /// <summary>
        /// Gets or Sets TextObjectType
        /// </summary>
        [DataMember(Name = "TextObjectType", IsRequired = true, EmitDefaultValue = true)]
        public string TextObjectType { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name = "Language", IsRequired = true, EmitDefaultValue = true)]
        public string Language { get; set; }

        /// <summary>
        /// Gets or Sets OrderComponentLongText
        /// </summary>
        [DataMember(Name = "OrderComponentLongText", EmitDefaultValue = true)]
        public string OrderComponentLongText { get; set; }

        /// <summary>
        /// Gets or Sets ToMaintenanceOrder
        /// </summary>
        [DataMember(Name = "to_MaintenanceOrder", EmitDefaultValue = false)]
        public MaintenanceOrderCreate ToMaintenanceOrder { get; set; }

        /// <summary>
        /// Gets or Sets ToMaintenanceOrderComponent
        /// </summary>
        [DataMember(Name = "to_MaintenanceOrderComponent", EmitDefaultValue = false)]
        public MaintenanceOrderOperationComponentEntityCreate ToMaintenanceOrderComponent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintenanceOrderOperationComponentLongTextCreate {\n");
            sb.Append("  TextObjectType: ").Append(TextObjectType).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  OrderComponentLongText: ").Append(OrderComponentLongText).Append("\n");
            sb.Append("  ToMaintenanceOrder: ").Append(ToMaintenanceOrder).Append("\n");
            sb.Append("  ToMaintenanceOrderComponent: ").Append(ToMaintenanceOrderComponent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TextObjectType (string) maxLength
            if (this.TextObjectType != null && this.TextObjectType.Length > 4)
            {
                yield return new ValidationResult("Invalid value for TextObjectType, length must be less than 4.", new [] { "TextObjectType" });
            }

            // Language (string) maxLength
            if (this.Language != null && this.Language.Length > 2)
            {
                yield return new ValidationResult("Invalid value for Language, length must be less than 2.", new [] { "Language" });
            }

            yield break;
        }
    }

}

