/*
 * Maintenance Order
 *
 * This service enables you to create, read, updated and delete maintenance order data. It contains order header, operation, component, object list item, operation relationship, long text and settlement rule nodes. The service is based on the OData V2 protocol, and can be consumed in external systems, Fiori applications and on other user interfaces.    If there are any issues when retrieving the maintenance order data, the system displays appropriate warning or error messages in the response.
 *
 * The version of the OpenAPI document: 2.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sap.Client.OpenAPIDateConverter;

namespace Sap.Model.MaintenanceOrder
{
    /// <summary>
    /// MaintenanceOrderOperationPRTEntityCreate
    /// </summary>
    [DataContract(Name = "cds_api_maintenanceorder_2.MaintOrderOpProdnRsceTool_Type-create")]
    public partial class MaintenanceOrderOperationPRTEntityCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceOrderOperationPRTEntityCreate" /> class.
        /// </summary>
        /// <param name="orderProdnRsceToolText">First Line of Text for Production Resources/Tools.</param>
        /// <param name="prodnRsceToolCategory">Production Resources/Tools Category.</param>
        /// <param name="product">Material Number.</param>
        /// <param name="miscProductionResourceTool">Miscellaneous Production Resources and Tools.</param>
        /// <param name="prodnRsceToolControlProfile">Control Profile for Management of Production Resources/Tools.</param>
        /// <param name="prodnRsceToolStandardWorkQty">Standard Value for Quantity of Production Resources/Tools.</param>
        /// <param name="prodnRsceToolStdWorkQtyUnit">Unit for Quantity of Production Resources/Tools.</param>
        /// <param name="plant">plant.</param>
        /// <param name="toMaintenanceOrderOperation">toMaintenanceOrderOperation.</param>
        /// <param name="toMaintenanceOrder">toMaintenanceOrder.</param>
        public MaintenanceOrderOperationPRTEntityCreate(string orderProdnRsceToolText = default(string), string prodnRsceToolCategory = default(string), string product = default(string), string miscProductionResourceTool = default(string), string prodnRsceToolControlProfile = default(string), decimal? prodnRsceToolStandardWorkQty = default(decimal?), string prodnRsceToolStdWorkQtyUnit = default(string), string plant = default(string), MaintenanceOrderOperationEntityCreate toMaintenanceOrderOperation = default(MaintenanceOrderOperationEntityCreate), MaintenanceOrderCreate toMaintenanceOrder = default(MaintenanceOrderCreate))
        {
            this.OrderProdnRsceToolText = orderProdnRsceToolText;
            this.ProdnRsceToolCategory = prodnRsceToolCategory;
            this.Product = product;
            this.MiscProductionResourceTool = miscProductionResourceTool;
            this.ProdnRsceToolControlProfile = prodnRsceToolControlProfile;
            this.ProdnRsceToolStandardWorkQty = prodnRsceToolStandardWorkQty;
            this.ProdnRsceToolStdWorkQtyUnit = prodnRsceToolStdWorkQtyUnit;
            this.Plant = plant;
            this.ToMaintenanceOrderOperation = toMaintenanceOrderOperation;
            this.ToMaintenanceOrder = toMaintenanceOrder;
        }

        /// <summary>
        /// First Line of Text for Production Resources/Tools
        /// </summary>
        /// <value>First Line of Text for Production Resources/Tools</value>
        [DataMember(Name = "OrderProdnRsceToolText", EmitDefaultValue = true)]
        public string OrderProdnRsceToolText { get; set; }

        /// <summary>
        /// Production Resources/Tools Category
        /// </summary>
        /// <value>Production Resources/Tools Category</value>
        [DataMember(Name = "ProdnRsceToolCategory", EmitDefaultValue = false)]
        public string ProdnRsceToolCategory { get; set; }

        /// <summary>
        /// Material Number
        /// </summary>
        /// <value>Material Number</value>
        [DataMember(Name = "Product", EmitDefaultValue = true)]
        public string Product { get; set; }

        /// <summary>
        /// Miscellaneous Production Resources and Tools
        /// </summary>
        /// <value>Miscellaneous Production Resources and Tools</value>
        [DataMember(Name = "MiscProductionResourceTool", EmitDefaultValue = true)]
        public string MiscProductionResourceTool { get; set; }

        /// <summary>
        /// Control Profile for Management of Production Resources/Tools
        /// </summary>
        /// <value>Control Profile for Management of Production Resources/Tools</value>
        [DataMember(Name = "ProdnRsceToolControlProfile", EmitDefaultValue = true)]
        public string ProdnRsceToolControlProfile { get; set; }

        /// <summary>
        /// Standard Value for Quantity of Production Resources/Tools
        /// </summary>
        /// <value>Standard Value for Quantity of Production Resources/Tools</value>
        /// <example>0</example>
        [DataMember(Name = "ProdnRsceToolStandardWorkQty", EmitDefaultValue = true)]
        public decimal? ProdnRsceToolStandardWorkQty { get; set; }

        /// <summary>
        /// Unit for Quantity of Production Resources/Tools
        /// </summary>
        /// <value>Unit for Quantity of Production Resources/Tools</value>
        [DataMember(Name = "ProdnRsceToolStdWorkQtyUnit", EmitDefaultValue = true)]
        public string ProdnRsceToolStdWorkQtyUnit { get; set; }

        /// <summary>
        /// Gets or Sets Plant
        /// </summary>
        [DataMember(Name = "Plant", EmitDefaultValue = true)]
        public string Plant { get; set; }

        /// <summary>
        /// Gets or Sets ToMaintenanceOrderOperation
        /// </summary>
        [DataMember(Name = "to_MaintenanceOrderOperation", EmitDefaultValue = false)]
        public MaintenanceOrderOperationEntityCreate ToMaintenanceOrderOperation { get; set; }

        /// <summary>
        /// Gets or Sets ToMaintenanceOrder
        /// </summary>
        [DataMember(Name = "to_MaintenanceOrder", EmitDefaultValue = false)]
        public MaintenanceOrderCreate ToMaintenanceOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintenanceOrderOperationPRTEntityCreate {\n");
            sb.Append("  OrderProdnRsceToolText: ").Append(OrderProdnRsceToolText).Append("\n");
            sb.Append("  ProdnRsceToolCategory: ").Append(ProdnRsceToolCategory).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  MiscProductionResourceTool: ").Append(MiscProductionResourceTool).Append("\n");
            sb.Append("  ProdnRsceToolControlProfile: ").Append(ProdnRsceToolControlProfile).Append("\n");
            sb.Append("  ProdnRsceToolStandardWorkQty: ").Append(ProdnRsceToolStandardWorkQty).Append("\n");
            sb.Append("  ProdnRsceToolStdWorkQtyUnit: ").Append(ProdnRsceToolStdWorkQtyUnit).Append("\n");
            sb.Append("  Plant: ").Append(Plant).Append("\n");
            sb.Append("  ToMaintenanceOrderOperation: ").Append(ToMaintenanceOrderOperation).Append("\n");
            sb.Append("  ToMaintenanceOrder: ").Append(ToMaintenanceOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // OrderProdnRsceToolText (string) maxLength
            if (this.OrderProdnRsceToolText != null && this.OrderProdnRsceToolText.Length > 40)
            {
                yield return new ValidationResult("Invalid value for OrderProdnRsceToolText, length must be less than 40.", new [] { "OrderProdnRsceToolText" });
            }

            // ProdnRsceToolCategory (string) maxLength
            if (this.ProdnRsceToolCategory != null && this.ProdnRsceToolCategory.Length > 1)
            {
                yield return new ValidationResult("Invalid value for ProdnRsceToolCategory, length must be less than 1.", new [] { "ProdnRsceToolCategory" });
            }

            // Product (string) maxLength
            if (this.Product != null && this.Product.Length > 40)
            {
                yield return new ValidationResult("Invalid value for Product, length must be less than 40.", new [] { "Product" });
            }

            // MiscProductionResourceTool (string) maxLength
            if (this.MiscProductionResourceTool != null && this.MiscProductionResourceTool.Length > 18)
            {
                yield return new ValidationResult("Invalid value for MiscProductionResourceTool, length must be less than 18.", new [] { "MiscProductionResourceTool" });
            }

            // ProdnRsceToolControlProfile (string) maxLength
            if (this.ProdnRsceToolControlProfile != null && this.ProdnRsceToolControlProfile.Length > 4)
            {
                yield return new ValidationResult("Invalid value for ProdnRsceToolControlProfile, length must be less than 4.", new [] { "ProdnRsceToolControlProfile" });
            }

            // ProdnRsceToolStdWorkQtyUnit (string) maxLength
            if (this.ProdnRsceToolStdWorkQtyUnit != null && this.ProdnRsceToolStdWorkQtyUnit.Length > 3)
            {
                yield return new ValidationResult("Invalid value for ProdnRsceToolStdWorkQtyUnit, length must be less than 3.", new [] { "ProdnRsceToolStdWorkQtyUnit" });
            }

            // Plant (string) maxLength
            if (this.Plant != null && this.Plant.Length > 4)
            {
                yield return new ValidationResult("Invalid value for Plant, length must be less than 4.", new [] { "Plant" });
            }

            yield break;
        }
    }

}

