/*
 * Maintenance Order
 *
 * This service enables you to create, read, updated and delete maintenance order data. It contains order header, operation, component, object list item, operation relationship, long text and settlement rule nodes. The service is based on the OData V2 protocol, and can be consumed in external systems, Fiori applications and on other user interfaces.    If there are any issues when retrieving the maintenance order data, the system displays appropriate warning or error messages in the response.
 *
 * The version of the OpenAPI document: 2.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Sap.Client.OpenAPIDateConverter;

namespace Sap.Model.MaintenanceOrder
{
    /// <summary>
    /// MaintenanceOrderPartnerEntity
    /// </summary>
    [DataContract(Name = "cds_api_maintenanceorder_2.MaintenanceOrderPartner_Type")]
    public partial class MaintenanceOrderPartnerEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceOrderPartnerEntity" /> class.
        /// </summary>
        /// <param name="maintenanceOrder">Order Number.</param>
        /// <param name="partnerFunction">partnerFunction.</param>
        /// <param name="maintenanceOrderPartner">maintenanceOrderPartner.</param>
        /// <param name="toMaintenanceOrder">toMaintenanceOrder.</param>
        public MaintenanceOrderPartnerEntity(string maintenanceOrder = default(string), string partnerFunction = default(string), string maintenanceOrderPartner = default(string), MaintenanceOrderEntity toMaintenanceOrder = default(MaintenanceOrderEntity))
        {
            this.MaintenanceOrder = maintenanceOrder;
            this.PartnerFunction = partnerFunction;
            this.MaintenanceOrderPartner = maintenanceOrderPartner;
            this.ToMaintenanceOrder = toMaintenanceOrder;
        }

        /// <summary>
        /// Order Number
        /// </summary>
        /// <value>Order Number</value>
        [DataMember(Name = "MaintenanceOrder", EmitDefaultValue = false)]
        public string MaintenanceOrder { get; set; }

        /// <summary>
        /// Gets or Sets PartnerFunction
        /// </summary>
        [DataMember(Name = "PartnerFunction", EmitDefaultValue = false)]
        public string PartnerFunction { get; set; }

        /// <summary>
        /// Gets or Sets MaintenanceOrderPartner
        /// </summary>
        [DataMember(Name = "MaintenanceOrderPartner", EmitDefaultValue = false)]
        public string MaintenanceOrderPartner { get; set; }

        /// <summary>
        /// Gets or Sets ToMaintenanceOrder
        /// </summary>
        [DataMember(Name = "to_MaintenanceOrder", EmitDefaultValue = false)]
        public MaintenanceOrderEntity ToMaintenanceOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintenanceOrderPartnerEntity {\n");
            sb.Append("  MaintenanceOrder: ").Append(MaintenanceOrder).Append("\n");
            sb.Append("  PartnerFunction: ").Append(PartnerFunction).Append("\n");
            sb.Append("  MaintenanceOrderPartner: ").Append(MaintenanceOrderPartner).Append("\n");
            sb.Append("  ToMaintenanceOrder: ").Append(ToMaintenanceOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaintenanceOrder (string) maxLength
            if (this.MaintenanceOrder != null && this.MaintenanceOrder.Length > 12)
            {
                yield return new ValidationResult("Invalid value for MaintenanceOrder, length must be less than 12.", new [] { "MaintenanceOrder" });
            }

            // PartnerFunction (string) maxLength
            if (this.PartnerFunction != null && this.PartnerFunction.Length > 2)
            {
                yield return new ValidationResult("Invalid value for PartnerFunction, length must be less than 2.", new [] { "PartnerFunction" });
            }

            // MaintenanceOrderPartner (string) maxLength
            if (this.MaintenanceOrderPartner != null && this.MaintenanceOrderPartner.Length > 12)
            {
                yield return new ValidationResult("Invalid value for MaintenanceOrderPartner, length must be less than 12.", new [] { "MaintenanceOrderPartner" });
            }

            yield break;
        }
    }

}

