/*
 * Maintenance Notification
 *
 * This service contains maintenance notification header details, item, item cause, item activity, and partner function. The information is sent in the request as a payload.    The request payload contains all information required to create or update a maintenance notification. All the information in the payload is used to create or update a maintenance notification including appropriate checks for restricted values and authorizations. Once the maintenance notification has been created, the notification number is sent in the response with the data included.    If the input in the request is not as expected when you create or update a maintenance notification, the system displays appropriate error or warning messages in the response.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Sap.Model.MaintenanceNotification
{
    /// <summary>
    /// MaintNotificationMaintenanceNotificationPartnerTypeCreate
    /// </summary>
    [DataContract(Name = "cds_api_maintnotification.MaintenanceNotificationPartnerWrapper-create")]
    public partial class MaintNotificationMaintenanceNotificationPartnerTypeCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintNotificationMaintenanceNotificationPartnerTypeCreate" /> class.
        /// </summary>
        [JsonConstructor]
        protected MaintNotificationMaintenanceNotificationPartnerTypeCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintNotificationMaintenanceNotificationPartnerTypeCreate" /> class.
        /// </summary>
        /// <param name="maintenanceNotification">Notification Number (required).</param>
        /// <param name="partnerFunction">partnerFunction (required).</param>
        /// <param name="notificationPartnerObjectNmbr">Counter for differentiation 6-digit (required).</param>
        /// <param name="partner">partner.</param>
        /// <param name="toNotif">toNotif.</param>
        public MaintNotificationMaintenanceNotificationPartnerTypeCreate(string maintenanceNotification = default(string), string partnerFunction = default(string), string notificationPartnerObjectNmbr = default(string), string partner = default(string), MaintNotificationMaintenanceNotificationTypeCreate toNotif = default(MaintNotificationMaintenanceNotificationTypeCreate))
        {
            // to ensure "maintenanceNotification" is required (not null)
            if (maintenanceNotification == null)
            {
                throw new ArgumentNullException("maintenanceNotification is a required property for MaintNotificationMaintenanceNotificationPartnerTypeCreate and cannot be null");
            }
            this.MaintenanceNotification = maintenanceNotification;
            // to ensure "partnerFunction" is required (not null)
            if (partnerFunction == null)
            {
                throw new ArgumentNullException("partnerFunction is a required property for MaintNotificationMaintenanceNotificationPartnerTypeCreate and cannot be null");
            }
            this.PartnerFunction = partnerFunction;
            // to ensure "notificationPartnerObjectNmbr" is required (not null)
            if (notificationPartnerObjectNmbr == null)
            {
                throw new ArgumentNullException("notificationPartnerObjectNmbr is a required property for MaintNotificationMaintenanceNotificationPartnerTypeCreate and cannot be null");
            }
            this.NotificationPartnerObjectNmbr = notificationPartnerObjectNmbr;
            this.Partner = partner;
            this.ToNotif = toNotif;
        }

        /// <summary>
        /// Notification Number
        /// </summary>
        /// <value>Notification Number</value>
        [DataMember(Name = "MaintenanceNotification", IsRequired = true, EmitDefaultValue = true)]
        public string MaintenanceNotification { get; set; }

        /// <summary>
        /// Gets or Sets PartnerFunction
        /// </summary>
        [DataMember(Name = "PartnerFunction", IsRequired = true, EmitDefaultValue = true)]
        public string PartnerFunction { get; set; }

        /// <summary>
        /// Counter for differentiation 6-digit
        /// </summary>
        /// <value>Counter for differentiation 6-digit</value>
        [DataMember(Name = "NotificationPartnerObjectNmbr", IsRequired = true, EmitDefaultValue = true)]
        public string NotificationPartnerObjectNmbr { get; set; }

        /// <summary>
        /// Gets or Sets Partner
        /// </summary>
        [DataMember(Name = "Partner", EmitDefaultValue = false)]
        public string Partner { get; set; }

        /// <summary>
        /// Gets or Sets ToNotif
        /// </summary>
        [DataMember(Name = "to_Notif", EmitDefaultValue = false)]
        public MaintNotificationMaintenanceNotificationTypeCreate ToNotif { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintNotificationMaintenanceNotificationPartnerTypeCreate {\n");
            sb.Append("  MaintenanceNotification: ").Append(MaintenanceNotification).Append("\n");
            sb.Append("  PartnerFunction: ").Append(PartnerFunction).Append("\n");
            sb.Append("  NotificationPartnerObjectNmbr: ").Append(NotificationPartnerObjectNmbr).Append("\n");
            sb.Append("  Partner: ").Append(Partner).Append("\n");
            sb.Append("  ToNotif: ").Append(ToNotif).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaintenanceNotification (string) maxLength
            if (this.MaintenanceNotification != null && this.MaintenanceNotification.Length > 12)
            {
                yield return new ValidationResult("Invalid value for MaintenanceNotification, length must be less than 12.", new [] { "MaintenanceNotification" });
            }

            // PartnerFunction (string) maxLength
            if (this.PartnerFunction != null && this.PartnerFunction.Length > 2)
            {
                yield return new ValidationResult("Invalid value for PartnerFunction, length must be less than 2.", new [] { "PartnerFunction" });
            }

            // NotificationPartnerObjectNmbr (string) maxLength
            if (this.NotificationPartnerObjectNmbr != null && this.NotificationPartnerObjectNmbr.Length > 6)
            {
                yield return new ValidationResult("Invalid value for NotificationPartnerObjectNmbr, length must be less than 6.", new [] { "NotificationPartnerObjectNmbr" });
            }

            // Partner (string) maxLength
            if (this.Partner != null && this.Partner.Length > 12)
            {
                yield return new ValidationResult("Invalid value for Partner, length must be less than 12.", new [] { "Partner" });
            }

            yield break;
        }
    }

}
