/*
 * Maintenance Notification
 *
 * This service contains maintenance notification header details, item, item cause, item activity, and partner function. The information is sent in the request as a payload.    The request payload contains all information required to create or update a maintenance notification. All the information in the payload is used to create or update a maintenance notification including appropriate checks for restricted values and authorizations. Once the maintenance notification has been created, the notification number is sent in the response with the data included.    If the input in the request is not as expected when you create or update a maintenance notification, the system displays appropriate error or warning messages in the response.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.MaintenanceNotification
{
    /// <summary>
    /// MaintNotificationMaintNotificationItemCauseTypeUpdate
    /// </summary>
    [DataContract(Name = "cds_api_maintnotification.MaintenanceNotificationItemCauseWrapper-update")]
    public partial class MaintNotificationMaintNotificationItemCauseTypeUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintNotificationMaintNotificationItemCauseTypeUpdate" /> class.
        /// </summary>
        /// <param name="maintNotifCauseText">maintNotifCauseText.</param>
        /// <param name="maintNotifCauseCodeGroup">maintNotifCauseCodeGroup.</param>
        /// <param name="maintNotificationCauseCode">maintNotificationCauseCode.</param>
        /// <param name="maintNotificationRootCause">maintNotificationRootCause.</param>
        public MaintNotificationMaintNotificationItemCauseTypeUpdate(string maintNotifCauseText = default(string), string maintNotifCauseCodeGroup = default(string), string maintNotificationCauseCode = default(string), string maintNotificationRootCause = default(string))
        {
            this.MaintNotifCauseText = maintNotifCauseText;
            this.MaintNotifCauseCodeGroup = maintNotifCauseCodeGroup;
            this.MaintNotificationCauseCode = maintNotificationCauseCode;
            this.MaintNotificationRootCause = maintNotificationRootCause;
        }

        /// <summary>
        /// Gets or Sets MaintNotifCauseText
        /// </summary>
        [DataMember(Name = "MaintNotifCauseText", EmitDefaultValue = true)]
        public string MaintNotifCauseText { get; set; }

        /// <summary>
        /// Gets or Sets MaintNotifCauseCodeGroup
        /// </summary>
        [DataMember(Name = "MaintNotifCauseCodeGroup", EmitDefaultValue = true)]
        public string MaintNotifCauseCodeGroup { get; set; }

        /// <summary>
        /// Gets or Sets MaintNotificationCauseCode
        /// </summary>
        [DataMember(Name = "MaintNotificationCauseCode", EmitDefaultValue = true)]
        public string MaintNotificationCauseCode { get; set; }

        /// <summary>
        /// Gets or Sets MaintNotificationRootCause
        /// </summary>
        [DataMember(Name = "MaintNotificationRootCause", EmitDefaultValue = true)]
        public string MaintNotificationRootCause { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintNotificationMaintNotificationItemCauseTypeUpdate {\n");
            sb.Append("  MaintNotifCauseText: ").Append(MaintNotifCauseText).Append("\n");
            sb.Append("  MaintNotifCauseCodeGroup: ").Append(MaintNotifCauseCodeGroup).Append("\n");
            sb.Append("  MaintNotificationCauseCode: ").Append(MaintNotificationCauseCode).Append("\n");
            sb.Append("  MaintNotificationRootCause: ").Append(MaintNotificationRootCause).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MaintNotifCauseText (string) maxLength
            if (this.MaintNotifCauseText != null && this.MaintNotifCauseText.Length > 40)
            {
                yield return new ValidationResult("Invalid value for MaintNotifCauseText, length must be less than 40.", new [] { "MaintNotifCauseText" });
            }

            // MaintNotifCauseCodeGroup (string) maxLength
            if (this.MaintNotifCauseCodeGroup != null && this.MaintNotifCauseCodeGroup.Length > 8)
            {
                yield return new ValidationResult("Invalid value for MaintNotifCauseCodeGroup, length must be less than 8.", new [] { "MaintNotifCauseCodeGroup" });
            }

            // MaintNotificationCauseCode (string) maxLength
            if (this.MaintNotificationCauseCode != null && this.MaintNotificationCauseCode.Length > 4)
            {
                yield return new ValidationResult("Invalid value for MaintNotificationCauseCode, length must be less than 4.", new [] { "MaintNotificationCauseCode" });
            }

            // MaintNotificationRootCause (string) maxLength
            if (this.MaintNotificationRootCause != null && this.MaintNotificationRootCause.Length > 1)
            {
                yield return new ValidationResult("Invalid value for MaintNotificationRootCause, length must be less than 1.", new [] { "MaintNotificationRootCause" });
            }

            yield break;
        }
    }

}
