/*
 * Maintenance Notification
 *
 * This service contains maintenance notification header details, item, item cause, item activity, and partner function. The information is sent in the request as a payload.    The request payload contains all information required to create or update a maintenance notification. All the information in the payload is used to create or update a maintenance notification including appropriate checks for restricted values and authorizations. Once the maintenance notification has been created, the notification number is sent in the response with the data included.    If the input in the request is not as expected when you create or update a maintenance notification, the system displays appropriate error or warning messages in the response.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.MaintenanceNotification
{
    /// <summary>
    /// MaintenanceNotificationItemCollection
    /// </summary>
    [DataContract(Name = "Collection_of_MaintenanceNotificationItemType")]
    public partial class MaintenanceNotificationItemCollection : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MaintenanceNotificationItemCollection" /> class.
        /// </summary>
        /// <param name="count">The number of entities in the collection. Available when using the [$inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) query option..</param>
        /// <param name="results">results.</param>
        public MaintenanceNotificationItemCollection(string count = default(string), List<MaintenanceNotificationItemEntity> results = default(List<MaintenanceNotificationItemEntity>))
        {
            this.Count = count;
            this.Results = results;
        }

        /// <summary>
        /// The number of entities in the collection. Available when using the [$inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) query option.
        /// </summary>
        /// <value>The number of entities in the collection. Available when using the [$inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) query option.</value>
        [DataMember(Name = "__count", EmitDefaultValue = false)]
        public string Count { get; set; }

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<MaintenanceNotificationItemEntity> Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MaintenanceNotificationItemCollection {\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
