/*
 * Supplier Invoice
 *
 * This service enables you to create supplier invoices through an API call from a source system. Furthermore the service enables you to read, release, reverse and post existing supplier invoices from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.5.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using Sap.Client;
using Sap.Model;
using Sap.Model.SupplierInvoice;

namespace Sap.Api.SupplierInvoice
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOfficialDocumentNumberApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SupplierInvoiceODNWrapper</returns>
        SupplierInvoiceODNWrapper ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0);

        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SupplierInvoiceODNWrapper</returns>
        ApiResponse<SupplierInvoiceODNWrapper> ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetWithHttpInfo(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0);
        /// <summary>
        /// Get entities from A_SupplierInvoiceODN
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SupplierInvoiceODNCollectionWrapper</returns>
        SupplierInvoiceODNCollectionWrapper ASupplierInvoiceODNGet(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0);

        /// <summary>
        /// Get entities from A_SupplierInvoiceODN
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SupplierInvoiceODNCollectionWrapper</returns>
        ApiResponse<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceODNGetWithHttpInfo(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0);
        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SupplierInvoiceODNCollectionWrapper</returns>
        SupplierInvoiceODNCollectionWrapper ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0);

        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SupplierInvoiceODNCollectionWrapper</returns>
        ApiResponse<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetWithHttpInfo(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOfficialDocumentNumberApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SupplierInvoiceODNWrapper</returns>
        System.Threading.Tasks.Task<SupplierInvoiceODNWrapper> ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetAsync(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SupplierInvoiceODNWrapper)</returns>
        System.Threading.Tasks.Task<ApiResponse<SupplierInvoiceODNWrapper>> ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetWithHttpInfoAsync(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get entities from A_SupplierInvoiceODN
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SupplierInvoiceODNCollectionWrapper</returns>
        System.Threading.Tasks.Task<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceODNGetAsync(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get entities from A_SupplierInvoiceODN
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SupplierInvoiceODNCollectionWrapper)</returns>
        System.Threading.Tasks.Task<ApiResponse<SupplierInvoiceODNCollectionWrapper>> ASupplierInvoiceODNGetWithHttpInfoAsync(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SupplierInvoiceODNCollectionWrapper</returns>
        System.Threading.Tasks.Task<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetAsync(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SupplierInvoiceODNCollectionWrapper)</returns>
        System.Threading.Tasks.Task<ApiResponse<SupplierInvoiceODNCollectionWrapper>> ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetWithHttpInfoAsync(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IOfficialDocumentNumberApi : IOfficialDocumentNumberApiSync, IOfficialDocumentNumberApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class OfficialDocumentNumberApi : IOfficialDocumentNumberApi
    {
        private Sap.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="OfficialDocumentNumberApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OfficialDocumentNumberApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OfficialDocumentNumberApi"/> class.
        /// </summary>
        /// <returns></returns>
        public OfficialDocumentNumberApi(string basePath)
        {
            this.Configuration = Sap.Client.Configuration.MergeConfigurations(
                Sap.Client.GlobalConfiguration.Instance,
                new Sap.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Sap.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Sap.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Sap.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OfficialDocumentNumberApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public OfficialDocumentNumberApi(Sap.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Sap.Client.Configuration.MergeConfigurations(
                Sap.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Sap.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Sap.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Sap.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OfficialDocumentNumberApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public OfficialDocumentNumberApi(Sap.Client.ISynchronousClient client, Sap.Client.IAsynchronousClient asyncClient, Sap.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Sap.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Sap.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Sap.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Sap.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Sap.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SupplierInvoiceODNWrapper</returns>
        public SupplierInvoiceODNWrapper ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0)
        {
            Sap.Client.ApiResponse<SupplierInvoiceODNWrapper> localVarResponse = ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetWithHttpInfo(aFDFUniqueKeyUUID, supplierInvoice, fiscalYear, select);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SupplierInvoiceODNWrapper</returns>
        public Sap.Client.ApiResponse<SupplierInvoiceODNWrapper> ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetWithHttpInfo(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0)
        {
            // verify the required parameter 'supplierInvoice' is set
            if (supplierInvoice == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'supplierInvoice' when calling OfficialDocumentNumberApi->ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet");
            }

            // verify the required parameter 'fiscalYear' is set
            if (fiscalYear == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'fiscalYear' when calling OfficialDocumentNumberApi->ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet");
            }

            Sap.Client.RequestOptions localVarRequestOptions = new Sap.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Sap.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Sap.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AFDFUniqueKeyUUID", Sap.Client.ClientUtils.ParameterToString(aFDFUniqueKeyUUID)); // path parameter
            localVarRequestOptions.PathParameters.Add("SupplierInvoice", Sap.Client.ClientUtils.ParameterToString(supplierInvoice)); // path parameter
            localVarRequestOptions.PathParameters.Add("FiscalYear", Sap.Client.ClientUtils.ParameterToString(fiscalYear)); // path parameter
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }

            localVarRequestOptions.Operation = "OfficialDocumentNumberApi.ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Sap.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SupplierInvoiceODNWrapper>("/A_SupplierInvoiceODN(AFDFUniqueKeyUUID=guid'{AFDFUniqueKeyUUID}',SupplierInvoice='{SupplierInvoice}',FiscalYear='{FiscalYear}')", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SupplierInvoiceODNWrapper</returns>
        public async System.Threading.Tasks.Task<SupplierInvoiceODNWrapper> ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetAsync(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Sap.Client.ApiResponse<SupplierInvoiceODNWrapper> localVarResponse = await ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetWithHttpInfoAsync(aFDFUniqueKeyUUID, supplierInvoice, fiscalYear, select, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get entity from A_SupplierInvoiceODN by key 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="aFDFUniqueKeyUUID">Globally Unique Identifier</param>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SupplierInvoiceODNWrapper)</returns>
        public async System.Threading.Tasks.Task<Sap.Client.ApiResponse<SupplierInvoiceODNWrapper>> ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGetWithHttpInfoAsync(Guid aFDFUniqueKeyUUID, string supplierInvoice, string fiscalYear, List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'supplierInvoice' is set
            if (supplierInvoice == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'supplierInvoice' when calling OfficialDocumentNumberApi->ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet");
            }

            // verify the required parameter 'fiscalYear' is set
            if (fiscalYear == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'fiscalYear' when calling OfficialDocumentNumberApi->ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet");
            }


            Sap.Client.RequestOptions localVarRequestOptions = new Sap.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Sap.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Sap.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("AFDFUniqueKeyUUID", Sap.Client.ClientUtils.ParameterToString(aFDFUniqueKeyUUID)); // path parameter
            localVarRequestOptions.PathParameters.Add("SupplierInvoice", Sap.Client.ClientUtils.ParameterToString(supplierInvoice)); // path parameter
            localVarRequestOptions.PathParameters.Add("FiscalYear", Sap.Client.ClientUtils.ParameterToString(fiscalYear)); // path parameter
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }

            localVarRequestOptions.Operation = "OfficialDocumentNumberApi.ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Sap.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<SupplierInvoiceODNWrapper>("/A_SupplierInvoiceODN(AFDFUniqueKeyUUID=guid'{AFDFUniqueKeyUUID}',SupplierInvoice='{SupplierInvoice}',FiscalYear='{FiscalYear}')", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ASupplierInvoiceODNAFDFUniqueKeyUUIDguidAFDFUniqueKeyUUIDSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get entities from A_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SupplierInvoiceODNCollectionWrapper</returns>
        public SupplierInvoiceODNCollectionWrapper ASupplierInvoiceODNGet(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0)
        {
            Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper> localVarResponse = ASupplierInvoiceODNGetWithHttpInfo(top, skip, filter, inlinecount, orderby, select);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get entities from A_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SupplierInvoiceODNCollectionWrapper</returns>
        public Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceODNGetWithHttpInfo(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0)
        {
            Sap.Client.RequestOptions localVarRequestOptions = new Sap.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Sap.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Sap.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (top != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$top", top));
            }
            if (skip != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$skip", skip));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$filter", filter));
            }
            if (inlinecount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$inlinecount", inlinecount));
            }
            if (orderby != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$orderby", orderby));
            }
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }

            localVarRequestOptions.Operation = "OfficialDocumentNumberApi.ASupplierInvoiceODNGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Sap.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SupplierInvoiceODNCollectionWrapper>("/A_SupplierInvoiceODN", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ASupplierInvoiceODNGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get entities from A_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SupplierInvoiceODNCollectionWrapper</returns>
        public async System.Threading.Tasks.Task<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceODNGetAsync(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper> localVarResponse = await ASupplierInvoiceODNGetWithHttpInfoAsync(top, skip, filter, inlinecount, orderby, select, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get entities from A_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SupplierInvoiceODNCollectionWrapper)</returns>
        public async System.Threading.Tasks.Task<Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper>> ASupplierInvoiceODNGetWithHttpInfoAsync(int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Sap.Client.RequestOptions localVarRequestOptions = new Sap.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Sap.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Sap.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (top != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$top", top));
            }
            if (skip != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$skip", skip));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$filter", filter));
            }
            if (inlinecount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$inlinecount", inlinecount));
            }
            if (orderby != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$orderby", orderby));
            }
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }

            localVarRequestOptions.Operation = "OfficialDocumentNumberApi.ASupplierInvoiceODNGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Sap.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<SupplierInvoiceODNCollectionWrapper>("/A_SupplierInvoiceODN", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ASupplierInvoiceODNGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SupplierInvoiceODNCollectionWrapper</returns>
        public SupplierInvoiceODNCollectionWrapper ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0)
        {
            Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper> localVarResponse = ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetWithHttpInfo(supplierInvoice, fiscalYear, top, skip, filter, inlinecount, orderby, select);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SupplierInvoiceODNCollectionWrapper</returns>
        public Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetWithHttpInfo(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0)
        {
            // verify the required parameter 'supplierInvoice' is set
            if (supplierInvoice == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'supplierInvoice' when calling OfficialDocumentNumberApi->ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet");
            }

            // verify the required parameter 'fiscalYear' is set
            if (fiscalYear == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'fiscalYear' when calling OfficialDocumentNumberApi->ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet");
            }

            Sap.Client.RequestOptions localVarRequestOptions = new Sap.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Sap.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Sap.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("SupplierInvoice", Sap.Client.ClientUtils.ParameterToString(supplierInvoice)); // path parameter
            localVarRequestOptions.PathParameters.Add("FiscalYear", Sap.Client.ClientUtils.ParameterToString(fiscalYear)); // path parameter
            if (top != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$top", top));
            }
            if (skip != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$skip", skip));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$filter", filter));
            }
            if (inlinecount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$inlinecount", inlinecount));
            }
            if (orderby != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$orderby", orderby));
            }
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }

            localVarRequestOptions.Operation = "OfficialDocumentNumberApi.ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Sap.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<SupplierInvoiceODNCollectionWrapper>("/A_SupplierInvoice(SupplierInvoice='{SupplierInvoice}',FiscalYear='{FiscalYear}')/to_SupplierInvoiceODN", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SupplierInvoiceODNCollectionWrapper</returns>
        public async System.Threading.Tasks.Task<SupplierInvoiceODNCollectionWrapper> ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetAsync(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper> localVarResponse = await ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetWithHttpInfoAsync(supplierInvoice, fiscalYear, top, skip, filter, inlinecount, orderby, select, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get entities from related to_SupplierInvoiceODN 
        /// </summary>
        /// <exception cref="Sap.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="supplierInvoice">Document Number of an Invoice Document</param>
        /// <param name="fiscalYear">Fiscal Year</param>
        /// <param name="top">Show only the first n items, see [Paging - Top](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;66) (optional)</param>
        /// <param name="skip">Skip the first n items, see [Paging - Skip](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="filter">Filter items by property values, see [Filtering](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;64) (optional)</param>
        /// <param name="inlinecount">Include count of items, see [Inlinecount](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;67) (optional)</param>
        /// <param name="orderby">Order items by property values, see [Sorting](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;65) (optional)</param>
        /// <param name="select">Select properties to be returned, see [Select](https://help.sap.com/doc/5890d27be418427993fafa6722cdc03b/Cloud/en-US/OdataV2.pdf#page&#x3D;68) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SupplierInvoiceODNCollectionWrapper)</returns>
        public async System.Threading.Tasks.Task<Sap.Client.ApiResponse<SupplierInvoiceODNCollectionWrapper>> ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGetWithHttpInfoAsync(string supplierInvoice, string fiscalYear, int? top = default(int?), int? skip = default(int?), string? filter = default(string?), string? inlinecount = default(string?), List<string>? orderby = default(List<string>?), List<string>? select = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'supplierInvoice' is set
            if (supplierInvoice == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'supplierInvoice' when calling OfficialDocumentNumberApi->ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet");
            }

            // verify the required parameter 'fiscalYear' is set
            if (fiscalYear == null)
            {
                throw new Sap.Client.ApiException(400, "Missing required parameter 'fiscalYear' when calling OfficialDocumentNumberApi->ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet");
            }


            Sap.Client.RequestOptions localVarRequestOptions = new Sap.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Sap.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Sap.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("SupplierInvoice", Sap.Client.ClientUtils.ParameterToString(supplierInvoice)); // path parameter
            localVarRequestOptions.PathParameters.Add("FiscalYear", Sap.Client.ClientUtils.ParameterToString(fiscalYear)); // path parameter
            if (top != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$top", top));
            }
            if (skip != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$skip", skip));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$filter", filter));
            }
            if (inlinecount != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("", "$inlinecount", inlinecount));
            }
            if (orderby != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$orderby", orderby));
            }
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(Sap.Client.ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }

            localVarRequestOptions.Operation = "OfficialDocumentNumberApi.ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Sap.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<SupplierInvoiceODNCollectionWrapper>("/A_SupplierInvoice(SupplierInvoice='{SupplierInvoice}',FiscalYear='{FiscalYear}')/to_SupplierInvoiceODN", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ASupplierInvoiceSupplierInvoiceSupplierInvoiceFiscalYearFiscalYearToSupplierInvoiceODNGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
