/*
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using Sap.Client;
using Sap.Model.PurchaseOrder;
using Sap.Model;

namespace Sap.Api.PurchaseOrder
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IItemDeliveryAddressApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0);

        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchWithHttpInfo(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0);
        /// <summary>
        /// Get related _PurchaseOrder
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PurchaseOrderPurchaseOrderType</returns>
        PurchaseOrderPurchaseOrderType PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0);

        /// <summary>
        /// Get related _PurchaseOrder
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PurchaseOrderPurchaseOrderType</returns>
        ApiResponse<PurchaseOrderPurchaseOrderType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetWithHttpInfo(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0);
        /// <summary>
        /// Get related _PurchaseOrderItem
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PurchaseOrderPurchaseOrderItemType</returns>
        PurchaseOrderPurchaseOrderItemType PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0);

        /// <summary>
        /// Get related _PurchaseOrderItem
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PurchaseOrderPurchaseOrderItemType</returns>
        ApiResponse<PurchaseOrderPurchaseOrderItemType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetWithHttpInfo(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IItemDeliveryAddressApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchWithHttpInfoAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get related _PurchaseOrder
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseOrderPurchaseOrderType</returns>
        System.Threading.Tasks.Task<PurchaseOrderPurchaseOrderType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get related _PurchaseOrder
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseOrderPurchaseOrderType)</returns>
        System.Threading.Tasks.Task<ApiResponse<PurchaseOrderPurchaseOrderType>> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetWithHttpInfoAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get related _PurchaseOrderItem
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseOrderPurchaseOrderItemType</returns>
        System.Threading.Tasks.Task<PurchaseOrderPurchaseOrderItemType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get related _PurchaseOrderItem
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseOrderPurchaseOrderItemType)</returns>
        System.Threading.Tasks.Task<ApiResponse<PurchaseOrderPurchaseOrderItemType>> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetWithHttpInfoAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IItemDeliveryAddressApi : IItemDeliveryAddressApiSync, IItemDeliveryAddressApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ItemDeliveryAddressApi : IItemDeliveryAddressApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemDeliveryAddressApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ItemDeliveryAddressApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemDeliveryAddressApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ItemDeliveryAddressApi(string basePath)
        {
            this.Configuration = Sap.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                new Configuration { BasePath = basePath }
            );
            this.Client = new ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Sap.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemDeliveryAddressApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ItemDeliveryAddressApi(Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Sap.Client.Configuration.MergeConfigurations(
                GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Sap.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemDeliveryAddressApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ItemDeliveryAddressApi(ISynchronousClient client, IAsynchronousClient asyncClient, IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Sap.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0)
        {
            PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchWithHttpInfo(purchaseOrder, purchaseOrderItem, deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate);
        }

        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchWithHttpInfo(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0)
        {
            // verify the required parameter 'purchaseOrder' is set
            if (purchaseOrder == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrder' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }

            // verify the required parameter 'purchaseOrderItem' is set
            if (purchaseOrderItem == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrderItem' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }

            // verify the required parameter 'deliveryAddressID' is set
            if (deliveryAddressID == null)
            {
                throw new ApiException(400, "Missing required parameter 'deliveryAddressID' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }

            // verify the required parameter 'PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate' is set
            if (PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate == null)
            {
                throw new ApiException(400, "Missing required parameter 'PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }

            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("PurchaseOrder", ClientUtils.ParameterToString(purchaseOrder)); // path parameter
            localVarRequestOptions.PathParameters.Add("PurchaseOrderItem", ClientUtils.ParameterToString(purchaseOrderItem)); // path parameter
            localVarRequestOptions.PathParameters.Add("DeliveryAddressID", ClientUtils.ParameterToString(deliveryAddressID)); // path parameter
            localVarRequestOptions.Data = PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate;

            localVarRequestOptions.Operation = "ItemDeliveryAddressApi.PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<Object>("/PurOrderItemDeliveryAddress/{PurchaseOrder}/{PurchaseOrderItem}/{DeliveryAddressID}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchWithHttpInfoAsync(purchaseOrder, purchaseOrderItem, deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Update entity in PurOrderItemDeliveryAddress 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate">New property values</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatchWithHttpInfoAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'purchaseOrder' is set
            if (purchaseOrder == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrder' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }

            // verify the required parameter 'purchaseOrderItem' is set
            if (purchaseOrderItem == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrderItem' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }

            // verify the required parameter 'deliveryAddressID' is set
            if (deliveryAddressID == null)
            {
                throw new ApiException(400, "Missing required parameter 'deliveryAddressID' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }

            // verify the required parameter 'PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate' is set
            if (PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate == null)
            {
                throw new ApiException(400, "Missing required parameter 'PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch");
            }


            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("PurchaseOrder", ClientUtils.ParameterToString(purchaseOrder)); // path parameter
            localVarRequestOptions.PathParameters.Add("PurchaseOrderItem", ClientUtils.ParameterToString(purchaseOrderItem)); // path parameter
            localVarRequestOptions.PathParameters.Add("DeliveryAddressID", ClientUtils.ParameterToString(deliveryAddressID)); // path parameter
            localVarRequestOptions.Data = PurchaseOrderPurOrderItemDeliveryAddressTypeUpdate;

            localVarRequestOptions.Operation = "ItemDeliveryAddressApi.PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<Object>("/PurOrderItemDeliveryAddress/{PurchaseOrder}/{PurchaseOrderItem}/{DeliveryAddressID}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get related _PurchaseOrder 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PurchaseOrderPurchaseOrderType</returns>
        public PurchaseOrderPurchaseOrderType PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0)
        {
            ApiResponse<PurchaseOrderPurchaseOrderType> localVarResponse = PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetWithHttpInfo(purchaseOrder, purchaseOrderItem, deliveryAddressID, select, expand);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get related _PurchaseOrder 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PurchaseOrderPurchaseOrderType</returns>
        public ApiResponse<PurchaseOrderPurchaseOrderType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetWithHttpInfo(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0)
        {
            // verify the required parameter 'purchaseOrder' is set
            if (purchaseOrder == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrder' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet");
            }

            // verify the required parameter 'purchaseOrderItem' is set
            if (purchaseOrderItem == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrderItem' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet");
            }

            // verify the required parameter 'deliveryAddressID' is set
            if (deliveryAddressID == null)
            {
                throw new ApiException(400, "Missing required parameter 'deliveryAddressID' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet");
            }

            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("PurchaseOrder", ClientUtils.ParameterToString(purchaseOrder)); // path parameter
            localVarRequestOptions.PathParameters.Add("PurchaseOrderItem", ClientUtils.ParameterToString(purchaseOrderItem)); // path parameter
            localVarRequestOptions.PathParameters.Add("DeliveryAddressID", ClientUtils.ParameterToString(deliveryAddressID)); // path parameter
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }
            if (expand != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$expand", expand));
            }

            localVarRequestOptions.Operation = "ItemDeliveryAddressApi.PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PurchaseOrderPurchaseOrderType>("/PurOrderItemDeliveryAddress/{PurchaseOrder}/{PurchaseOrderItem}/{DeliveryAddressID}/_PurchaseOrder", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get related _PurchaseOrder 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseOrderPurchaseOrderType</returns>
        public async System.Threading.Tasks.Task<PurchaseOrderPurchaseOrderType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ApiResponse<PurchaseOrderPurchaseOrderType> localVarResponse = await PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetWithHttpInfoAsync(purchaseOrder, purchaseOrderItem, deliveryAddressID, select, expand, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get related _PurchaseOrder 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseOrderPurchaseOrderType)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PurchaseOrderPurchaseOrderType>> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGetWithHttpInfoAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'purchaseOrder' is set
            if (purchaseOrder == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrder' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet");
            }

            // verify the required parameter 'purchaseOrderItem' is set
            if (purchaseOrderItem == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrderItem' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet");
            }

            // verify the required parameter 'deliveryAddressID' is set
            if (deliveryAddressID == null)
            {
                throw new ApiException(400, "Missing required parameter 'deliveryAddressID' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet");
            }


            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("PurchaseOrder", ClientUtils.ParameterToString(purchaseOrder)); // path parameter
            localVarRequestOptions.PathParameters.Add("PurchaseOrderItem", ClientUtils.ParameterToString(purchaseOrderItem)); // path parameter
            localVarRequestOptions.PathParameters.Add("DeliveryAddressID", ClientUtils.ParameterToString(deliveryAddressID)); // path parameter
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }
            if (expand != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$expand", expand));
            }

            localVarRequestOptions.Operation = "ItemDeliveryAddressApi.PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PurchaseOrderPurchaseOrderType>("/PurOrderItemDeliveryAddress/{PurchaseOrder}/{PurchaseOrderItem}/{DeliveryAddressID}/_PurchaseOrder", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get related _PurchaseOrderItem 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PurchaseOrderPurchaseOrderItemType</returns>
        public PurchaseOrderPurchaseOrderItemType PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0)
        {
            ApiResponse<PurchaseOrderPurchaseOrderItemType> localVarResponse = PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetWithHttpInfo(purchaseOrder, purchaseOrderItem, deliveryAddressID, select, expand);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get related _PurchaseOrderItem 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PurchaseOrderPurchaseOrderItemType</returns>
        public ApiResponse<PurchaseOrderPurchaseOrderItemType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetWithHttpInfo(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0)
        {
            // verify the required parameter 'purchaseOrder' is set
            if (purchaseOrder == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrder' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet");
            }

            // verify the required parameter 'purchaseOrderItem' is set
            if (purchaseOrderItem == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrderItem' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet");
            }

            // verify the required parameter 'deliveryAddressID' is set
            if (deliveryAddressID == null)
            {
                throw new ApiException(400, "Missing required parameter 'deliveryAddressID' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet");
            }

            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("PurchaseOrder", ClientUtils.ParameterToString(purchaseOrder)); // path parameter
            localVarRequestOptions.PathParameters.Add("PurchaseOrderItem", ClientUtils.ParameterToString(purchaseOrderItem)); // path parameter
            localVarRequestOptions.PathParameters.Add("DeliveryAddressID", ClientUtils.ParameterToString(deliveryAddressID)); // path parameter
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }
            if (expand != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$expand", expand));
            }

            localVarRequestOptions.Operation = "ItemDeliveryAddressApi.PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PurchaseOrderPurchaseOrderItemType>("/PurOrderItemDeliveryAddress/{PurchaseOrder}/{PurchaseOrderItem}/{DeliveryAddressID}/_PurchaseOrderItem", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get related _PurchaseOrderItem 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PurchaseOrderPurchaseOrderItemType</returns>
        public async System.Threading.Tasks.Task<PurchaseOrderPurchaseOrderItemType> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            ApiResponse<PurchaseOrderPurchaseOrderItemType> localVarResponse = await PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetWithHttpInfoAsync(purchaseOrder, purchaseOrderItem, deliveryAddressID, select, expand, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get related _PurchaseOrderItem 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="purchaseOrder">Purchasing Document Number</param>
        /// <param name="purchaseOrderItem">Item Number of Purchase Order</param>
        /// <param name="deliveryAddressID">Manual address number in purchasing document item</param>
        /// <param name="select">Select properties to be returned, see [Select](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionselect) (optional)</param>
        /// <param name="expand">Expand related entities, see [Expand](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_SystemQueryOptionexpand) (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PurchaseOrderPurchaseOrderItemType)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PurchaseOrderPurchaseOrderItemType>> PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGetWithHttpInfoAsync(string purchaseOrder, string purchaseOrderItem, string deliveryAddressID, List<string>? select = default(List<string>?), List<string>? expand = default(List<string>?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'purchaseOrder' is set
            if (purchaseOrder == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrder' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet");
            }

            // verify the required parameter 'purchaseOrderItem' is set
            if (purchaseOrderItem == null)
            {
                throw new ApiException(400, "Missing required parameter 'purchaseOrderItem' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet");
            }

            // verify the required parameter 'deliveryAddressID' is set
            if (deliveryAddressID == null)
            {
                throw new ApiException(400, "Missing required parameter 'deliveryAddressID' when calling ItemDeliveryAddressApi->PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet");
            }


            RequestOptions localVarRequestOptions = new RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("PurchaseOrder", ClientUtils.ParameterToString(purchaseOrder)); // path parameter
            localVarRequestOptions.PathParameters.Add("PurchaseOrderItem", ClientUtils.ParameterToString(purchaseOrderItem)); // path parameter
            localVarRequestOptions.PathParameters.Add("DeliveryAddressID", ClientUtils.ParameterToString(deliveryAddressID)); // path parameter
            if (select != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$select", select));
            }
            if (expand != null)
            {
                localVarRequestOptions.QueryParameters.Add(ClientUtils.ParameterToMultiMap("csv", "$expand", expand));
            }

            localVarRequestOptions.Operation = "ItemDeliveryAddressApi.PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (BasicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
            // authentication (OAuth2Auth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PurchaseOrderPurchaseOrderItemType>("/PurOrderItemDeliveryAddress/{PurchaseOrder}/{PurchaseOrderItem}/{DeliveryAddressID}/_PurchaseOrderItem", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PurOrderItemDeliveryAddressPurchaseOrderPurchaseOrderItemDeliveryAddressIDPurchaseOrderItemGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}

