/*
 * Environment, Health and Safety EhsIncident - Create, Read
 *
 * This service contains the basic information about an EhsIncident as the main entity, and persons involved, EhsLocationWrapper, and attachments as dependent entities. For create operations, the information is sent in the request as a payload, except for EhsAttachmentWrapper-related data. You can add attachments to the newly created EhsIncident in separate calls. Once the EhsIncident has been created, the EhsIncident data and global identification are sent in the response. For read operations, filter information can be sent according to the OData protocol. While creating an EhsIncident or retrieving EhsIncident data, the system performs checks for restricted values and authorization. If there are any issues, the system displays error messages in the response.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Sap.Model.EHSIncident
{
    /// <summary>
    /// EhsIncidentCEHSPersonValueHelpTypeCreate
    /// </summary>
    [DataContract(Name = "API_EHS_REPORT_INCIDENT_SRV.C_EHSPersonValueHelpType-create")]
    public partial class EhsIncidentCEHSPersonValueHelpTypeCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EhsIncidentCEHSPersonValueHelpTypeCreate" /> class.
        /// </summary>
        [JsonConstructor]
        protected EhsIncidentCEHSPersonValueHelpTypeCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EhsIncidentCEHSPersonValueHelpTypeCreate" /> class.
        /// </summary>
        /// <param name="businessPartner">Business Partner Number (required).</param>
        /// <param name="personWorkAgreement">personWorkAgreement.</param>
        /// <param name="eHSCombinedBusinessPartner">eHSCombinedBusinessPartner.</param>
        /// <param name="firstName">First Name of Business Partner (EhsPersonWrapper).</param>
        /// <param name="lastName">Last Name of Business Partner (EhsPersonWrapper).</param>
        /// <param name="businessPartnerName">businessPartnerName.</param>
        /// <param name="bPFirstNameSearchHelp">Search Help Field 2 (Name 2/First Name).</param>
        /// <param name="bPLastNameSearchHelp">Search Help Field 1 (Name 1/Last Name).</param>
        /// <param name="organizationalUnit">Organizational Unit.</param>
        /// <param name="companyCode">companyCode.</param>
        /// <param name="companyCodeName">Name of Company Code or Company.</param>
        /// <param name="jobName">jobName.</param>
        /// <param name="organizationalUnitName">organizationalUnitName.</param>
        /// <param name="orgManagementPositionName">orgManagementPositionName.</param>
        public EhsIncidentCEHSPersonValueHelpTypeCreate(string businessPartner = default(string), string personWorkAgreement = default(string), string eHSCombinedBusinessPartner = default(string), string firstName = default(string), string lastName = default(string), string businessPartnerName = default(string), string bPFirstNameSearchHelp = default(string), string bPLastNameSearchHelp = default(string), string organizationalUnit = default(string), string companyCode = default(string), string companyCodeName = default(string), string jobName = default(string), string organizationalUnitName = default(string), string orgManagementPositionName = default(string))
        {
            // to ensure "businessPartner" is required (not null)
            if (businessPartner == null)
            {
                throw new ArgumentNullException("businessPartner is a required property for EhsIncidentCEHSPersonValueHelpTypeCreate and cannot be null");
            }
            this.BusinessPartner = businessPartner;
            this.PersonWorkAgreement = personWorkAgreement;
            this.EHSCombinedBusinessPartner = eHSCombinedBusinessPartner;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.BusinessPartnerName = businessPartnerName;
            this.BPFirstNameSearchHelp = bPFirstNameSearchHelp;
            this.BPLastNameSearchHelp = bPLastNameSearchHelp;
            this.OrganizationalUnit = organizationalUnit;
            this.CompanyCode = companyCode;
            this.CompanyCodeName = companyCodeName;
            this.JobName = jobName;
            this.OrganizationalUnitName = organizationalUnitName;
            this.OrgManagementPositionName = orgManagementPositionName;
        }

        /// <summary>
        /// Business Partner Number
        /// </summary>
        /// <value>Business Partner Number</value>
        [DataMember(Name = "BusinessPartner", IsRequired = true, EmitDefaultValue = true)]
        public string BusinessPartner { get; set; }

        /// <summary>
        /// Gets or Sets PersonWorkAgreement
        /// </summary>
        [DataMember(Name = "PersonWorkAgreement", EmitDefaultValue = true)]
        public string PersonWorkAgreement { get; set; }

        /// <summary>
        /// Gets or Sets EHSCombinedBusinessPartner
        /// </summary>
        [DataMember(Name = "EHSCombinedBusinessPartner", EmitDefaultValue = true)]
        public string EHSCombinedBusinessPartner { get; set; }

        /// <summary>
        /// First Name of Business Partner (EhsPersonWrapper)
        /// </summary>
        /// <value>First Name of Business Partner (EhsPersonWrapper)</value>
        [DataMember(Name = "FirstName", EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Last Name of Business Partner (EhsPersonWrapper)
        /// </summary>
        /// <value>Last Name of Business Partner (EhsPersonWrapper)</value>
        [DataMember(Name = "LastName", EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets BusinessPartnerName
        /// </summary>
        [DataMember(Name = "BusinessPartnerName", EmitDefaultValue = true)]
        public string BusinessPartnerName { get; set; }

        /// <summary>
        /// Search Help Field 2 (Name 2/First Name)
        /// </summary>
        /// <value>Search Help Field 2 (Name 2/First Name)</value>
        [DataMember(Name = "BPFirstNameSearchHelp", EmitDefaultValue = true)]
        public string BPFirstNameSearchHelp { get; set; }

        /// <summary>
        /// Search Help Field 1 (Name 1/Last Name)
        /// </summary>
        /// <value>Search Help Field 1 (Name 1/Last Name)</value>
        [DataMember(Name = "BPLastNameSearchHelp", EmitDefaultValue = true)]
        public string BPLastNameSearchHelp { get; set; }

        /// <summary>
        /// Organizational Unit
        /// </summary>
        /// <value>Organizational Unit</value>
        [DataMember(Name = "OrganizationalUnit", EmitDefaultValue = true)]
        public string OrganizationalUnit { get; set; }

        /// <summary>
        /// Gets or Sets CompanyCode
        /// </summary>
        [DataMember(Name = "CompanyCode", EmitDefaultValue = true)]
        public string CompanyCode { get; set; }

        /// <summary>
        /// Name of Company Code or Company
        /// </summary>
        /// <value>Name of Company Code or Company</value>
        [DataMember(Name = "CompanyCodeName", EmitDefaultValue = true)]
        public string CompanyCodeName { get; set; }

        /// <summary>
        /// Gets or Sets JobName
        /// </summary>
        [DataMember(Name = "JobName", EmitDefaultValue = true)]
        public string JobName { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationalUnitName
        /// </summary>
        [DataMember(Name = "OrganizationalUnitName", EmitDefaultValue = true)]
        public string OrganizationalUnitName { get; set; }

        /// <summary>
        /// Gets or Sets OrgManagementPositionName
        /// </summary>
        [DataMember(Name = "OrgManagementPositionName", EmitDefaultValue = true)]
        public string OrgManagementPositionName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EhsIncidentCEHSPersonValueHelpTypeCreate {\n");
            sb.Append("  BusinessPartner: ").Append(BusinessPartner).Append("\n");
            sb.Append("  PersonWorkAgreement: ").Append(PersonWorkAgreement).Append("\n");
            sb.Append("  EHSCombinedBusinessPartner: ").Append(EHSCombinedBusinessPartner).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  BusinessPartnerName: ").Append(BusinessPartnerName).Append("\n");
            sb.Append("  BPFirstNameSearchHelp: ").Append(BPFirstNameSearchHelp).Append("\n");
            sb.Append("  BPLastNameSearchHelp: ").Append(BPLastNameSearchHelp).Append("\n");
            sb.Append("  OrganizationalUnit: ").Append(OrganizationalUnit).Append("\n");
            sb.Append("  CompanyCode: ").Append(CompanyCode).Append("\n");
            sb.Append("  CompanyCodeName: ").Append(CompanyCodeName).Append("\n");
            sb.Append("  JobName: ").Append(JobName).Append("\n");
            sb.Append("  OrganizationalUnitName: ").Append(OrganizationalUnitName).Append("\n");
            sb.Append("  OrgManagementPositionName: ").Append(OrgManagementPositionName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // BusinessPartner (string) maxLength
            if (this.BusinessPartner != null && this.BusinessPartner.Length > 10)
            {
                yield return new ValidationResult("Invalid value for BusinessPartner, length must be less than 10.", new [] { "BusinessPartner" });
            }

            // PersonWorkAgreement (string) maxLength
            if (this.PersonWorkAgreement != null && this.PersonWorkAgreement.Length > 8)
            {
                yield return new ValidationResult("Invalid value for PersonWorkAgreement, length must be less than 8.", new [] { "PersonWorkAgreement" });
            }

            // EHSCombinedBusinessPartner (string) maxLength
            if (this.EHSCombinedBusinessPartner != null && this.EHSCombinedBusinessPartner.Length > 13)
            {
                yield return new ValidationResult("Invalid value for EHSCombinedBusinessPartner, length must be less than 13.", new [] { "EHSCombinedBusinessPartner" });
            }

            // FirstName (string) maxLength
            if (this.FirstName != null && this.FirstName.Length > 40)
            {
                yield return new ValidationResult("Invalid value for FirstName, length must be less than 40.", new [] { "FirstName" });
            }

            // LastName (string) maxLength
            if (this.LastName != null && this.LastName.Length > 40)
            {
                yield return new ValidationResult("Invalid value for LastName, length must be less than 40.", new [] { "LastName" });
            }

            // BusinessPartnerName (string) maxLength
            if (this.BusinessPartnerName != null && this.BusinessPartnerName.Length > 81)
            {
                yield return new ValidationResult("Invalid value for BusinessPartnerName, length must be less than 81.", new [] { "BusinessPartnerName" });
            }

            // BPFirstNameSearchHelp (string) maxLength
            if (this.BPFirstNameSearchHelp != null && this.BPFirstNameSearchHelp.Length > 35)
            {
                yield return new ValidationResult("Invalid value for BPFirstNameSearchHelp, length must be less than 35.", new [] { "BPFirstNameSearchHelp" });
            }

            // BPLastNameSearchHelp (string) maxLength
            if (this.BPLastNameSearchHelp != null && this.BPLastNameSearchHelp.Length > 35)
            {
                yield return new ValidationResult("Invalid value for BPLastNameSearchHelp, length must be less than 35.", new [] { "BPLastNameSearchHelp" });
            }

            // OrganizationalUnit (string) maxLength
            if (this.OrganizationalUnit != null && this.OrganizationalUnit.Length > 8)
            {
                yield return new ValidationResult("Invalid value for OrganizationalUnit, length must be less than 8.", new [] { "OrganizationalUnit" });
            }

            // CompanyCode (string) maxLength
            if (this.CompanyCode != null && this.CompanyCode.Length > 4)
            {
                yield return new ValidationResult("Invalid value for CompanyCode, length must be less than 4.", new [] { "CompanyCode" });
            }

            // CompanyCodeName (string) maxLength
            if (this.CompanyCodeName != null && this.CompanyCodeName.Length > 25)
            {
                yield return new ValidationResult("Invalid value for CompanyCodeName, length must be less than 25.", new [] { "CompanyCodeName" });
            }

            // JobName (string) maxLength
            if (this.JobName != null && this.JobName.Length > 255)
            {
                yield return new ValidationResult("Invalid value for JobName, length must be less than 255.", new [] { "JobName" });
            }

            // OrganizationalUnitName (string) maxLength
            if (this.OrganizationalUnitName != null && this.OrganizationalUnitName.Length > 40)
            {
                yield return new ValidationResult("Invalid value for OrganizationalUnitName, length must be less than 40.", new [] { "OrganizationalUnitName" });
            }

            // OrgManagementPositionName (string) maxLength
            if (this.OrgManagementPositionName != null && this.OrgManagementPositionName.Length > 40)
            {
                yield return new ValidationResult("Invalid value for OrgManagementPositionName, length must be less than 40.", new [] { "OrgManagementPositionName" });
            }

            yield break;
        }
    }

}
