/*
 * Environment, Health and Safety EhsIncident - Create, Read
 *
 * This service contains the basic information about an EhsIncident as the main entity, and persons involved, EhsLocationWrapper, and attachments as dependent entities. For create operations, the information is sent in the request as a payload, except for EhsAttachmentWrapper-related data. You can add attachments to the newly created EhsIncident in separate calls. Once the EhsIncident has been created, the EhsIncident data and global identification are sent in the response. For read operations, filter information can be sent according to the OData protocol. While creating an EhsIncident or retrieving EhsIncident data, the system performs checks for restricted values and authorization. If there are any issues, the system displays error messages in the response.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Sap.Model.EHSIncident
{
    /// <summary>
    /// EhsIncidentIncidentCreate
    /// </summary>
    [DataContract(Name = "API_EHS_REPORT_INCIDENT_SRV.EhsIncident-create")]
    public partial class EhsIncidentIncidentCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EhsIncidentIncidentCreate" /> class.
        /// </summary>
        [JsonConstructor]
        protected EhsIncidentIncidentCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EhsIncidentIncidentCreate" /> class.
        /// </summary>
        /// <param name="incidentUUID">incidentUUID (required).</param>
        /// <param name="incidentUTCDateTime">incidentUTCDateTime.</param>
        /// <param name="incidentDescriptionOfEvents">incidentDescriptionOfEvents.</param>
        /// <param name="eHSLocationUUID">eHSLocationUUID.</param>
        /// <param name="toAttachments">toAttachments.</param>
        /// <param name="toPersons">toPersons.</param>
        /// <param name="toLocation">toLocation.</param>
        public EhsIncidentIncidentCreate(Guid incidentUUID = default(Guid), string incidentUTCDateTime = default(string), string incidentDescriptionOfEvents = default(string), Guid? eHSLocationUUID = default(Guid?), EhsIncidentIncidentCreateToAttachments toAttachments = default(EhsIncidentIncidentCreateToAttachments), EhsIncidentIncidentCreateToPersons toPersons = default(EhsIncidentIncidentCreateToPersons), Object toLocation = default(Object))
        {
            this.IncidentUUID = incidentUUID;
            this.IncidentUTCDateTime = incidentUTCDateTime;
            this.IncidentDescriptionOfEvents = incidentDescriptionOfEvents;
            this.EHSLocationUUID = eHSLocationUUID;
            this.ToAttachments = toAttachments;
            this.ToPersons = toPersons;
            this.ToLocation = toLocation;
        }

        /// <summary>
        /// Gets or Sets IncidentUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>
        [DataMember(Name = "IncidentUUID", IsRequired = true, EmitDefaultValue = true)]
        public Guid IncidentUUID { get; set; }

        /// <summary>
        /// Gets or Sets IncidentUTCDateTime
        /// </summary>
        /// <example>/Date(1492098664000)/</example>
        [DataMember(Name = "IncidentUTCDateTime", EmitDefaultValue = false)]
        public string IncidentUTCDateTime { get; set; }

        /// <summary>
        /// Gets or Sets IncidentDescriptionOfEvents
        /// </summary>
        [DataMember(Name = "IncidentDescriptionOfEvents", EmitDefaultValue = true)]
        public string IncidentDescriptionOfEvents { get; set; }

        /// <summary>
        /// Gets or Sets EHSLocationUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>
        [DataMember(Name = "EHSLocationUUID", EmitDefaultValue = true)]
        public Guid? EHSLocationUUID { get; set; }

        /// <summary>
        /// Gets or Sets ToAttachments
        /// </summary>
        [DataMember(Name = "to_Attachments", EmitDefaultValue = false)]
        public EhsIncidentIncidentCreateToAttachments ToAttachments { get; set; }

        /// <summary>
        /// Gets or Sets ToPersons
        /// </summary>
        [DataMember(Name = "to_Persons", EmitDefaultValue = false)]
        public EhsIncidentIncidentCreateToPersons ToPersons { get; set; }

        /// <summary>
        /// Gets or Sets ToLocation
        /// </summary>
        [DataMember(Name = "to_Location", EmitDefaultValue = true)]
        public Object ToLocation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EhsIncidentIncidentCreate {\n");
            sb.Append("  IncidentUUID: ").Append(IncidentUUID).Append("\n");
            sb.Append("  IncidentUTCDateTime: ").Append(IncidentUTCDateTime).Append("\n");
            sb.Append("  IncidentDescriptionOfEvents: ").Append(IncidentDescriptionOfEvents).Append("\n");
            sb.Append("  EHSLocationUUID: ").Append(EHSLocationUUID).Append("\n");
            sb.Append("  ToAttachments: ").Append(ToAttachments).Append("\n");
            sb.Append("  ToPersons: ").Append(ToPersons).Append("\n");
            sb.Append("  ToLocation: ").Append(ToLocation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // IncidentDescriptionOfEvents (string) maxLength
            if (this.IncidentDescriptionOfEvents != null && this.IncidentDescriptionOfEvents.Length > 999999)
            {
                yield return new ValidationResult("Invalid value for IncidentDescriptionOfEvents, length must be less than 999999.", new [] { "IncidentDescriptionOfEvents" });
            }

            yield break;
        }
    }

}
