/*
 * Environment, Health and Safety EhsIncident - Create, Read
 *
 * This service contains the basic information about an EhsIncident as the main entity, and persons involved, EhsLocationWrapper, and attachments as dependent entities. For create operations, the information is sent in the request as a payload, except for EhsAttachmentWrapper-related data. You can add attachments to the newly created EhsIncident in separate calls. Once the EhsIncident has been created, the EhsIncident data and global identification are sent in the response. For read operations, filter information can be sent according to the OData protocol. While creating an EhsIncident or retrieving EhsIncident data, the system performs checks for restricted values and authorization. If there are any issues, the system displays error messages in the response.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Sap.Model.EHSIncident
{
    /// <summary>
    /// EhsIncidentCCurEHSLocationInclRootHierTypeCreate
    /// </summary>
    [DataContract(Name = "API_EHS_REPORT_INCIDENT_SRV.C_CurEHSLocationInclRootHierType-create")]
    public partial class EhsIncidentCCurEHSLocationInclRootHierTypeCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EhsIncidentCCurEHSLocationInclRootHierTypeCreate" /> class.
        /// </summary>
        [JsonConstructor]
        protected EhsIncidentCCurEHSLocationInclRootHierTypeCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EhsIncidentCCurEHSLocationInclRootHierTypeCreate" /> class.
        /// </summary>
        /// <param name="eHSLocationUUID">eHSLocationUUID (required).</param>
        /// <param name="eHSLocationName">eHSLocationName.</param>
        /// <param name="eHSLocationIDAndName">Text (length 132).</param>
        /// <param name="eHSLocationID">EhsLocationWrapper ID.</param>
        /// <param name="eHSLocationTypeText">EhsLocationWrapper Type Description.</param>
        /// <param name="eHSLocationStatus">eHSLocationStatus.</param>
        /// <param name="plant">plant.</param>
        /// <param name="myEHSLocationUUID">myEHSLocationUUID.</param>
        /// <param name="eHSParentLocationUUID">eHSParentLocationUUID.</param>
        /// <param name="eHSLocationDrillStateString">Text (10 Characters).</param>
        /// <param name="eHSLocationType">eHSLocationType.</param>
        /// <param name="eHSLocationAuthorizationGroup">EhsLocationWrapper Authorization Group.</param>
        /// <param name="costCenter">costCenter.</param>
        /// <param name="companyCode">companyCode.</param>
        /// <param name="businessArea">businessArea.</param>
        /// <param name="eHSLocClassifiersText">List of Classifiers (Comma Separated) - short.</param>
        /// <param name="eHSLocHierarchyNodeUUID">eHSLocHierarchyNodeUUID.</param>
        /// <param name="eHSLocHierarchyParentNodeUUID">eHSLocHierarchyParentNodeUUID.</param>
        /// <param name="hierarchyLevel">hierarchyLevel.</param>
        public EhsIncidentCCurEHSLocationInclRootHierTypeCreate(Guid eHSLocationUUID = default(Guid), string eHSLocationName = default(string), string eHSLocationIDAndName = default(string), string eHSLocationID = default(string), string eHSLocationTypeText = default(string), string eHSLocationStatus = default(string), string plant = default(string), Guid? myEHSLocationUUID = default(Guid?), Guid? eHSParentLocationUUID = default(Guid?), string eHSLocationDrillStateString = default(string), string eHSLocationType = default(string), string eHSLocationAuthorizationGroup = default(string), string costCenter = default(string), string companyCode = default(string), string businessArea = default(string), string eHSLocClassifiersText = default(string), Guid? eHSLocHierarchyNodeUUID = default(Guid?), Guid? eHSLocHierarchyParentNodeUUID = default(Guid?), int? hierarchyLevel = default(int?))
        {
            this.EHSLocationUUID = eHSLocationUUID;
            this.EHSLocationName = eHSLocationName;
            this.EHSLocationIDAndName = eHSLocationIDAndName;
            this.EHSLocationID = eHSLocationID;
            this.EHSLocationTypeText = eHSLocationTypeText;
            this.EHSLocationStatus = eHSLocationStatus;
            this.Plant = plant;
            this.MyEHSLocationUUID = myEHSLocationUUID;
            this.EHSParentLocationUUID = eHSParentLocationUUID;
            this.EHSLocationDrillStateString = eHSLocationDrillStateString;
            this.EHSLocationType = eHSLocationType;
            this.EHSLocationAuthorizationGroup = eHSLocationAuthorizationGroup;
            this.CostCenter = costCenter;
            this.CompanyCode = companyCode;
            this.BusinessArea = businessArea;
            this.EHSLocClassifiersText = eHSLocClassifiersText;
            this.EHSLocHierarchyNodeUUID = eHSLocHierarchyNodeUUID;
            this.EHSLocHierarchyParentNodeUUID = eHSLocHierarchyParentNodeUUID;
            this.HierarchyLevel = hierarchyLevel;
        }

        /// <summary>
        /// Gets or Sets EHSLocationUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>
        [DataMember(Name = "EHSLocationUUID", IsRequired = true, EmitDefaultValue = true)]
        public Guid EHSLocationUUID { get; set; }

        /// <summary>
        /// Gets or Sets EHSLocationName
        /// </summary>
        [DataMember(Name = "EHSLocationName", EmitDefaultValue = true)]
        public string EHSLocationName { get; set; }

        /// <summary>
        /// Text (length 132)
        /// </summary>
        /// <value>Text (length 132)</value>
        [DataMember(Name = "EHSLocationIDAndName", EmitDefaultValue = true)]
        public string EHSLocationIDAndName { get; set; }

        /// <summary>
        /// EhsLocationWrapper ID
        /// </summary>
        /// <value>EhsLocationWrapper ID</value>
        [DataMember(Name = "EHSLocationID", EmitDefaultValue = true)]
        public string EHSLocationID { get; set; }

        /// <summary>
        /// EhsLocationWrapper Type Description
        /// </summary>
        /// <value>EhsLocationWrapper Type Description</value>
        [DataMember(Name = "EHSLocationTypeText", EmitDefaultValue = true)]
        public string EHSLocationTypeText { get; set; }

        /// <summary>
        /// Gets or Sets EHSLocationStatus
        /// </summary>
        [DataMember(Name = "EHSLocationStatus", EmitDefaultValue = true)]
        public string EHSLocationStatus { get; set; }

        /// <summary>
        /// Gets or Sets Plant
        /// </summary>
        [DataMember(Name = "Plant", EmitDefaultValue = true)]
        public string Plant { get; set; }

        /// <summary>
        /// Gets or Sets MyEHSLocationUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>
        [DataMember(Name = "MyEHSLocationUUID", EmitDefaultValue = true)]
        public Guid? MyEHSLocationUUID { get; set; }

        /// <summary>
        /// Gets or Sets EHSParentLocationUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>
        [DataMember(Name = "EHSParentLocationUUID", EmitDefaultValue = true)]
        public Guid? EHSParentLocationUUID { get; set; }

        /// <summary>
        /// Text (10 Characters)
        /// </summary>
        /// <value>Text (10 Characters)</value>
        [DataMember(Name = "EHSLocationDrillStateString", EmitDefaultValue = true)]
        public string EHSLocationDrillStateString { get; set; }

        /// <summary>
        /// Gets or Sets EHSLocationType
        /// </summary>
        [DataMember(Name = "EHSLocationType", EmitDefaultValue = true)]
        public string EHSLocationType { get; set; }

        /// <summary>
        /// EhsLocationWrapper Authorization Group
        /// </summary>
        /// <value>EhsLocationWrapper Authorization Group</value>
        [DataMember(Name = "EHSLocationAuthorizationGroup", EmitDefaultValue = true)]
        public string EHSLocationAuthorizationGroup { get; set; }

        /// <summary>
        /// Gets or Sets CostCenter
        /// </summary>
        [DataMember(Name = "CostCenter", EmitDefaultValue = true)]
        public string CostCenter { get; set; }

        /// <summary>
        /// Gets or Sets CompanyCode
        /// </summary>
        [DataMember(Name = "CompanyCode", EmitDefaultValue = true)]
        public string CompanyCode { get; set; }

        /// <summary>
        /// Gets or Sets BusinessArea
        /// </summary>
        [DataMember(Name = "BusinessArea", EmitDefaultValue = true)]
        public string BusinessArea { get; set; }

        /// <summary>
        /// List of Classifiers (Comma Separated) - short
        /// </summary>
        /// <value>List of Classifiers (Comma Separated) - short</value>
        [DataMember(Name = "EHSLocClassifiersText", EmitDefaultValue = true)]
        public string EHSLocClassifiersText { get; set; }

        /// <summary>
        /// Gets or Sets EHSLocHierarchyNodeUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>
        [DataMember(Name = "EHSLocHierarchyNodeUUID", EmitDefaultValue = true)]
        public Guid? EHSLocHierarchyNodeUUID { get; set; }

        /// <summary>
        /// Gets or Sets EHSLocHierarchyParentNodeUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>
        [DataMember(Name = "EHSLocHierarchyParentNodeUUID", EmitDefaultValue = true)]
        public Guid? EHSLocHierarchyParentNodeUUID { get; set; }

        /// <summary>
        /// Gets or Sets HierarchyLevel
        /// </summary>
        [DataMember(Name = "HierarchyLevel", EmitDefaultValue = true)]
        public int? HierarchyLevel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EhsIncidentCCurEHSLocationInclRootHierTypeCreate {\n");
            sb.Append("  EHSLocationUUID: ").Append(EHSLocationUUID).Append("\n");
            sb.Append("  EHSLocationName: ").Append(EHSLocationName).Append("\n");
            sb.Append("  EHSLocationIDAndName: ").Append(EHSLocationIDAndName).Append("\n");
            sb.Append("  EHSLocationID: ").Append(EHSLocationID).Append("\n");
            sb.Append("  EHSLocationTypeText: ").Append(EHSLocationTypeText).Append("\n");
            sb.Append("  EHSLocationStatus: ").Append(EHSLocationStatus).Append("\n");
            sb.Append("  Plant: ").Append(Plant).Append("\n");
            sb.Append("  MyEHSLocationUUID: ").Append(MyEHSLocationUUID).Append("\n");
            sb.Append("  EHSParentLocationUUID: ").Append(EHSParentLocationUUID).Append("\n");
            sb.Append("  EHSLocationDrillStateString: ").Append(EHSLocationDrillStateString).Append("\n");
            sb.Append("  EHSLocationType: ").Append(EHSLocationType).Append("\n");
            sb.Append("  EHSLocationAuthorizationGroup: ").Append(EHSLocationAuthorizationGroup).Append("\n");
            sb.Append("  CostCenter: ").Append(CostCenter).Append("\n");
            sb.Append("  CompanyCode: ").Append(CompanyCode).Append("\n");
            sb.Append("  BusinessArea: ").Append(BusinessArea).Append("\n");
            sb.Append("  EHSLocClassifiersText: ").Append(EHSLocClassifiersText).Append("\n");
            sb.Append("  EHSLocHierarchyNodeUUID: ").Append(EHSLocHierarchyNodeUUID).Append("\n");
            sb.Append("  EHSLocHierarchyParentNodeUUID: ").Append(EHSLocHierarchyParentNodeUUID).Append("\n");
            sb.Append("  HierarchyLevel: ").Append(HierarchyLevel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EHSLocationName (string) maxLength
            if (this.EHSLocationName != null && this.EHSLocationName.Length > 60)
            {
                yield return new ValidationResult("Invalid value for EHSLocationName, length must be less than 60.", new [] { "EHSLocationName" });
            }

            // EHSLocationIDAndName (string) maxLength
            if (this.EHSLocationIDAndName != null && this.EHSLocationIDAndName.Length > 132)
            {
                yield return new ValidationResult("Invalid value for EHSLocationIDAndName, length must be less than 132.", new [] { "EHSLocationIDAndName" });
            }

            // EHSLocationID (string) maxLength
            if (this.EHSLocationID != null && this.EHSLocationID.Length > 20)
            {
                yield return new ValidationResult("Invalid value for EHSLocationID, length must be less than 20.", new [] { "EHSLocationID" });
            }

            // EHSLocationTypeText (string) maxLength
            if (this.EHSLocationTypeText != null && this.EHSLocationTypeText.Length > 40)
            {
                yield return new ValidationResult("Invalid value for EHSLocationTypeText, length must be less than 40.", new [] { "EHSLocationTypeText" });
            }

            // EHSLocationStatus (string) maxLength
            if (this.EHSLocationStatus != null && this.EHSLocationStatus.Length > 20)
            {
                yield return new ValidationResult("Invalid value for EHSLocationStatus, length must be less than 20.", new [] { "EHSLocationStatus" });
            }

            // Plant (string) maxLength
            if (this.Plant != null && this.Plant.Length > 4)
            {
                yield return new ValidationResult("Invalid value for Plant, length must be less than 4.", new [] { "Plant" });
            }

            // EHSLocationDrillStateString (string) maxLength
            if (this.EHSLocationDrillStateString != null && this.EHSLocationDrillStateString.Length > 10)
            {
                yield return new ValidationResult("Invalid value for EHSLocationDrillStateString, length must be less than 10.", new [] { "EHSLocationDrillStateString" });
            }

            // EHSLocationType (string) maxLength
            if (this.EHSLocationType != null && this.EHSLocationType.Length > 40)
            {
                yield return new ValidationResult("Invalid value for EHSLocationType, length must be less than 40.", new [] { "EHSLocationType" });
            }

            // EHSLocationAuthorizationGroup (string) maxLength
            if (this.EHSLocationAuthorizationGroup != null && this.EHSLocationAuthorizationGroup.Length > 21)
            {
                yield return new ValidationResult("Invalid value for EHSLocationAuthorizationGroup, length must be less than 21.", new [] { "EHSLocationAuthorizationGroup" });
            }

            // CostCenter (string) maxLength
            if (this.CostCenter != null && this.CostCenter.Length > 10)
            {
                yield return new ValidationResult("Invalid value for CostCenter, length must be less than 10.", new [] { "CostCenter" });
            }

            // CompanyCode (string) maxLength
            if (this.CompanyCode != null && this.CompanyCode.Length > 4)
            {
                yield return new ValidationResult("Invalid value for CompanyCode, length must be less than 4.", new [] { "CompanyCode" });
            }

            // BusinessArea (string) maxLength
            if (this.BusinessArea != null && this.BusinessArea.Length > 4)
            {
                yield return new ValidationResult("Invalid value for BusinessArea, length must be less than 4.", new [] { "BusinessArea" });
            }

            // EHSLocClassifiersText (string) maxLength
            if (this.EHSLocClassifiersText != null && this.EHSLocClassifiersText.Length > 255)
            {
                yield return new ValidationResult("Invalid value for EHSLocClassifiersText, length must be less than 255.", new [] { "EHSLocClassifiersText" });
            }

            yield break;
        }
    }

}
