/*
 * Environment, Health and Safety EhsIncident - Create, Read
 *
 * This service contains the basic information about an EhsIncident as the main entity, and persons involved, EhsLocationWrapper, and attachments as dependent entities. For create operations, the information is sent in the request as a payload, except for EhsAttachmentWrapper-related data. You can add attachments to the newly created EhsIncident in separate calls. Once the EhsIncident has been created, the EhsIncident data and global identification are sent in the response. For read operations, filter information can be sent according to the OData protocol. While creating an EhsIncident or retrieving EhsIncident data, the system performs checks for restricted values and authorization. If there are any issues, the system displays error messages in the response.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.EHSIncident
{
    /// <summary>
    /// EhsIncidentIEHSLocClassifierTextTypeUpdate
    /// </summary>
    [DataContract(Name = "API_EHS_REPORT_INCIDENT_SRV.I_EHSLocClassifierTextType-update")]
    public partial class EhsIncidentIEHSLocClassifierTextTypeUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref = "EhsIncidentIEHSLocClassifierTextTypeUpdate"/> class.
        /// </summary>
        /// <param name = "eHSLocClassifierID">eHSLocClassifierID.</param>
        /// <param name = "eHSLocClassifierText">Translatable Long Text (255 char).</param>
        public EhsIncidentIEHSLocClassifierTextTypeUpdate(string eHSLocClassifierID = default(string), string eHSLocClassifierText = default(string))
        {
            this.EHSLocClassifierID = eHSLocClassifierID;
            this.EHSLocClassifierText = eHSLocClassifierText;
        }

        /// <summary>
        /// Gets or Sets EHSLocClassifierID
        /// </summary>
        [DataMember(Name = "EHSLocClassifierID", EmitDefaultValue = true)]
        public string EHSLocClassifierID { get; set; }

        /// <summary>
        /// Translatable Long Text (255 char)
        /// </summary>
        /// <value>Translatable Long Text (255 char)</value>
        [DataMember(Name = "EHSLocClassifierText", EmitDefaultValue = true)]
        public string EHSLocClassifierText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EhsIncidentIEHSLocClassifierTextTypeUpdate {\n");
            sb.Append("  EHSLocClassifierID: ").Append(EHSLocClassifierID).Append("\n");
            sb.Append("  EHSLocClassifierText: ").Append(EHSLocClassifierText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name = "validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // EHSLocClassifierID (string) maxLength
            if (this.EHSLocClassifierID != null && this.EHSLocClassifierID.Length > 40)
            {
                yield return new ValidationResult("Invalid value for EHSLocClassifierID, length must be less than 40.", new[] { "EHSLocClassifierID" });
            }

            // EHSLocClassifierText (string) maxLength
            if (this.EHSLocClassifierText != null && this.EHSLocClassifierText.Length > 255)
            {
                yield return new ValidationResult("Invalid value for EHSLocClassifierText, length must be less than 255.", new[] { "EHSLocClassifierText" });
            }

            yield break;
        }

        public EhsIncidentIEHSLocClassifierTextTypeUpdate()
        {
        }
    }
}
