/*
 * Environment, Health and Safety EhsIncident - Create, Read
 *
 * This service contains the basic information about an EhsIncident as the main entity, and persons involved, EhsLocationWrapper, and attachments as dependent entities. For create operations, the information is sent in the request as a payload, except for EhsAttachmentWrapper-related data. You can add attachments to the newly created EhsIncident in separate calls. Once the EhsIncident has been created, the EhsIncident data and global identification are sent in the response. For read operations, filter information can be sent according to the OData protocol. While creating an EhsIncident or retrieving EhsIncident data, the system performs checks for restricted values and authorization. If there are any issues, the system displays error messages in the response.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Sap.Model.EHSIncident
{
    /// <summary>
    /// EhsPersonEntity
    /// </summary>
    [DataContract(Name = "API_EHS_REPORT_INCIDENT_SRV.EhsPersonWrapper")]
    public partial class EhsPersonEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EhsPersonEntity" /> class.
        /// </summary>
        /// <param name="personInvolvedRoleDesc">personInvolvedRoleDesc.</param>
        /// <param name="personId">personId.</param>
        /// <param name="personFullName">personFullName.</param>
        /// <param name="personInvolvedRole">personInvolvedRole.</param>
        /// <param name="personInvolvedUUID">personInvolvedUUID.</param>
        /// <param name="metadata"></param>
        [JsonConstructor]
        public EhsPersonEntity( string personInvolvedRoleDesc = default(string), string personId = default(string), string personFullName = default(string), string personInvolvedRole = default(string), Guid personInvolvedUUID = default(Guid), Metadata metadata = default(Metadata))
        {
            this.PersonInvolvedRoleDesc = personInvolvedRoleDesc;
            this.PersonId = personId;
            this.PersonFullName = personFullName;
            this.PersonInvolvedRole = personInvolvedRole;
            this.PersonInvolvedUUID = personInvolvedUUID;
            //this.Metadata = metadata;
            // use default value if no "PersonInvolvedRoleDesc" provided
            if (personInvolvedRoleDesc == null)
            {
                this.PersonInvolvedRoleDesc = "PersonInvolvedRoleDesc";
            }
            // use default value if no "PersonId" provided
            if (personId == null)
            {
                this.PersonId = "PersonId";
            }
        }

        public EhsPersonEntity()
        {

        }

        public EhsPersonEntity(EhsPersonEntity EhsPersonWrapper)
        {
            this.PersonInvolvedUUID = EhsPersonWrapper.PersonInvolvedUUID;
            this.PersonInvolvedRoleDesc = EhsPersonWrapper.PersonInvolvedRoleDesc;
            this.PersonId = EhsPersonWrapper.PersonId;
            this.PersonFullName = EhsPersonWrapper.PersonFullName;
            this.PersonInvolvedRole = EhsPersonWrapper.PersonInvolvedRole;
            this.IncidentUUID = EhsPersonWrapper.IncidentUUID;
            //this.Metadata = EhsPersonWrapper.Metadata;
            // use default value if no "PersonInvolvedRoleDesc" provided
            if (EhsPersonWrapper.PersonInvolvedRoleDesc == null)
            {
                this.PersonInvolvedRoleDesc = "PersonInvolvedRoleDesc";
            }
            // use default value if no "PersonId" provided
            if (EhsPersonWrapper.PersonId == null)
            {
                this.PersonId = "PersonId";
            }
        }
        /// <summary>
        ///
        /// </summary>
        //[DataMember(Name = "__Metadata", EmitDefaultValue = true)]
       // public Metadata? Metadata { get; set; }


        /// <summary>
        /// Gets or Sets PersonInvolvedRoleDesc
        /// </summary>
        [DataMember(Name = "PersonInvolvedRoleDesc", EmitDefaultValue = false)]
        public string PersonInvolvedRoleDesc { get; set; }

        /// <summary>
        /// Gets or Sets PersonId
        /// </summary>
        [DataMember(Name = "PersonId", EmitDefaultValue = false)]
        public string PersonId { get; set; }

        /// <summary>
        /// Gets or Sets PersonFullName
        /// </summary>
        [DataMember(Name = "PersonFullName", EmitDefaultValue = false)]
        public string PersonFullName { get; set; }

        /// <summary>
        /// Gets or Sets PersonInvolvedRole
        /// </summary>
        [DataMember(Name = "PersonInvolvedRole", EmitDefaultValue = false)]
        public string PersonInvolvedRole { get; set; }

        /// <summary>
        /// Gets or Sets PersonInvolvedUUID
        /// </summary>
        /// <example>01234567-89ab-cdef-0123-456789abcdef</example>

        public Guid PersonInvolvedUUID { get; set; }
        /// <summary>
        ///
        /// </summary>
        [DataMember(Name = "IncidentUUID", EmitDefaultValue = false)]
        public Guid IncidentUUID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EhsPersonEntity {\n");
            sb.Append("  PersonInvolvedRoleDesc: ").Append(PersonInvolvedRoleDesc).Append("\n");
            sb.Append("  PersonId: ").Append(PersonId).Append("\n");
            sb.Append("  PersonFullName: ").Append(PersonFullName).Append("\n");
            sb.Append("  PersonInvolvedRole: ").Append(PersonInvolvedRole).Append("\n");
            sb.Append("  PersonInvolvedUUID: ").Append(PersonInvolvedUUID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PersonInvolvedRoleDesc (string) maxLength
            if (this.PersonInvolvedRoleDesc != null && this.PersonInvolvedRoleDesc.Length > 80)
            {
                yield return new ValidationResult("Invalid value for PersonInvolvedRoleDesc, length must be less than 80.", new [] { "PersonInvolvedRoleDesc" });
            }

            // PersonId (string) maxLength
            if (this.PersonId != null && this.PersonId.Length > 80)
            {
                yield return new ValidationResult("Invalid value for PersonId, length must be less than 80.", new [] { "PersonId" });
            }

            // PersonFullName (string) maxLength
            if (this.PersonFullName != null && this.PersonFullName.Length > 80)
            {
                yield return new ValidationResult("Invalid value for PersonFullName, length must be less than 80.", new [] { "PersonFullName" });
            }

            // PersonInvolvedRole (string) maxLength
            if (this.PersonInvolvedRole != null && this.PersonInvolvedRole.Length > 21)
            {
                yield return new ValidationResult("Invalid value for PersonInvolvedRole, length must be less than 21.", new [] { "PersonInvolvedRole" });
            }

            yield break;
        }
    }

}
