/*
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.PurchaseOrder
{
    /// <summary>
    /// CollectionOfPurOrderItemPricingElementType
    /// </summary>
    [DataContract(Name = "Collection_of_PurOrderItemPricingElement_Type")]
    public partial class CollectionOfPurOrderItemPricingElementType : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref = "CollectionOfPurOrderItemPricingElementType"/> class.
        /// </summary>
        /// <param name = "odataCount">odataCount.</param>
        /// <param name = "value">value.</param>
        public CollectionOfPurOrderItemPricingElementType(Count odataCount = default(Count), List<PurchaseOrderPurOrderItemPricingElementType> value = default(List<PurchaseOrderPurOrderItemPricingElementType>))
        {
            this.OdataCount = odataCount;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets OdataCount
        /// </summary>
        [DataMember(Name = "@odata.count", EmitDefaultValue = false)]
        public Count OdataCount { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public List<PurchaseOrderPurOrderItemPricingElementType> Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CollectionOfPurOrderItemPricingElementType {\n");
            sb.Append("  OdataCount: ").Append(OdataCount).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name = "validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }

        public CollectionOfPurOrderItemPricingElementType()
        {
        }
    }
}
