/*
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.PurchaseOrder
{
    /// <summary>
    /// PurchaseOrderPurchaseOrderInvoicingPlanTypeUpdate
    /// </summary>
    [DataContract(Name = "com.sap.gateway.srvd_a2x.api_purchaseorder_2.v0001.PurchaseOrderInvoicingPlan_Type-update")]
    public partial class PurchaseOrderPurchaseOrderInvoicingPlanTypeUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref = "PurchaseOrderPurchaseOrderInvoicingPlanTypeUpdate"/> class.
        /// </summary>
        /// <param name = "invoicingPlanType">Billing/Invoicing Plan Type.</param>
        /// <param name = "invoicingPlanStartDate">Start Date of Billing/Invoicing Plan.</param>
        /// <param name = "invoicingPlanEndDate">End Date of Billing/Invoicing Plan.</param>
        /// <param name = "invoicingPlanNextInvcDateRule">Rule for Origin of Next Billing/Invoice Date.</param>
        /// <param name = "purchasingOrganization">Purchasing Organization.</param>
        /// <param name = "purchasingGroup">purchasingGroup.</param>
        /// <param name = "PurchaseOrderWrapper">Purchasing Document Type.</param>
        /// <param name = "plant">plant.</param>
        /// <param name = "sAPMessages">sAPMessages.</param>
        public PurchaseOrderPurchaseOrderInvoicingPlanTypeUpdate(string invoicingPlanType = default(string), DateOnly? invoicingPlanStartDate = null, DateOnly? invoicingPlanEndDate = null, string invoicingPlanNextInvcDateRule = default(string), string purchasingOrganization = default(string), string purchasingGroup = default(string), string PurchaseOrderWrapper = default(string), string plant = default(string), List<PurchaseOrderSAPMessageUpdate> sAPMessages = default(List<PurchaseOrderSAPMessageUpdate>))
        {
            this.InvoicingPlanType = invoicingPlanType;
            this.InvoicingPlanStartDate = invoicingPlanStartDate;
            this.InvoicingPlanEndDate = invoicingPlanEndDate;
            this.InvoicingPlanNextInvcDateRule = invoicingPlanNextInvcDateRule;
            this.PurchasingOrganization = purchasingOrganization;
            this.PurchasingGroup = purchasingGroup;
            this.PurchaseOrderWrapper = PurchaseOrderWrapper;
            this.Plant = plant;
            this.SAPMessages = sAPMessages;
        }

        /// <summary>
        /// Billing/Invoicing Plan Type
        /// </summary>
        /// <value>Billing/Invoicing Plan Type</value>
        [DataMember(Name = "InvoicingPlanType", EmitDefaultValue = false)]
        public string InvoicingPlanType { get; set; }

        /// <summary>
        /// Start Date of Billing/Invoicing Plan
        /// </summary>
        /// <value>Start Date of Billing/Invoicing Plan</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "InvoicingPlanStartDate", EmitDefaultValue = true)]
        public DateOnly? InvoicingPlanStartDate { get; set; }

        /// <summary>
        /// End Date of Billing/Invoicing Plan
        /// </summary>
        /// <value>End Date of Billing/Invoicing Plan</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "InvoicingPlanEndDate", EmitDefaultValue = true)]
        public DateOnly? InvoicingPlanEndDate { get; set; }

        /// <summary>
        /// Rule for Origin of Next Billing/Invoice Date
        /// </summary>
        /// <value>Rule for Origin of Next Billing/Invoice Date</value>
        [DataMember(Name = "InvoicingPlanNextInvcDateRule", EmitDefaultValue = false)]
        public string InvoicingPlanNextInvcDateRule { get; set; }

        /// <summary>
        /// Purchasing Organization
        /// </summary>
        /// <value>Purchasing Organization</value>
        [DataMember(Name = "PurchasingOrganization", EmitDefaultValue = false)]
        public string PurchasingOrganization { get; set; }

        /// <summary>
        /// Gets or Sets PurchasingGroup
        /// </summary>
        [DataMember(Name = "PurchasingGroup", EmitDefaultValue = false)]
        public string PurchasingGroup { get; set; }

        /// <summary>
        /// Purchasing Document Type
        /// </summary>
        /// <value>Purchasing Document Type</value>
        [DataMember(Name = "PurchaseOrderWrapper", EmitDefaultValue = false)]
        public string PurchaseOrderWrapper { get; set; }

        /// <summary>
        /// Gets or Sets Plant
        /// </summary>
        [DataMember(Name = "Plant", EmitDefaultValue = false)]
        public string Plant { get; set; }

        /// <summary>
        /// Gets or Sets SAPMessages
        /// </summary>
        [DataMember(Name = "SAP__Messages", EmitDefaultValue = false)]
        public List<PurchaseOrderSAPMessageUpdate> SAPMessages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PurchaseOrderPurchaseOrderInvoicingPlanTypeUpdate {\n");
            sb.Append("  InvoicingPlanType: ").Append(InvoicingPlanType).Append("\n");
            sb.Append("  InvoicingPlanStartDate: ").Append(InvoicingPlanStartDate).Append("\n");
            sb.Append("  InvoicingPlanEndDate: ").Append(InvoicingPlanEndDate).Append("\n");
            sb.Append("  InvoicingPlanNextInvcDateRule: ").Append(InvoicingPlanNextInvcDateRule).Append("\n");
            sb.Append("  PurchasingOrganization: ").Append(PurchasingOrganization).Append("\n");
            sb.Append("  PurchasingGroup: ").Append(PurchasingGroup).Append("\n");
            sb.Append("  PurchaseOrderWrapper: ").Append(PurchaseOrderWrapper).Append("\n");
            sb.Append("  Plant: ").Append(Plant).Append("\n");
            sb.Append("  SAPMessages: ").Append(SAPMessages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name = "validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // InvoicingPlanType (string) maxLength
            if (this.InvoicingPlanType != null && this.InvoicingPlanType.Length > 2)
            {
                yield return new ValidationResult("Invalid value for InvoicingPlanType, length must be less than 2.", new[] { "InvoicingPlanType" });
            }

            // InvoicingPlanNextInvcDateRule (string) maxLength
            if (this.InvoicingPlanNextInvcDateRule != null && this.InvoicingPlanNextInvcDateRule.Length > 2)
            {
                yield return new ValidationResult("Invalid value for InvoicingPlanNextInvcDateRule, length must be less than 2.", new[] { "InvoicingPlanNextInvcDateRule" });
            }

            // PurchasingOrganization (string) maxLength
            if (this.PurchasingOrganization != null && this.PurchasingOrganization.Length > 4)
            {
                yield return new ValidationResult("Invalid value for PurchasingOrganization, length must be less than 4.", new[] { "PurchasingOrganization" });
            }

            // PurchasingGroup (string) maxLength
            if (this.PurchasingGroup != null && this.PurchasingGroup.Length > 3)
            {
                yield return new ValidationResult("Invalid value for PurchasingGroup, length must be less than 3.", new[] { "PurchasingGroup" });
            }

            // PurchaseOrderWrapper (string) maxLength
            if (this.PurchaseOrderWrapper != null && this.PurchaseOrderWrapper.Length > 4)
            {
                yield return new ValidationResult("Invalid value for PurchaseOrderWrapper, length must be less than 4.", new[] { "PurchaseOrderWrapper" });
            }

            // Plant (string) maxLength
            if (this.Plant != null && this.Plant.Length > 4)
            {
                yield return new ValidationResult("Invalid value for Plant, length must be less than 4.", new[] { "Plant" });
            }

            yield break;
        }

        public PurchaseOrderPurchaseOrderInvoicingPlanTypeUpdate()
        {
        }
    }
}
