/*
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Sap.Model.PurchaseOrder
{
    /// <summary>
    /// PurchaseOrderPurchaseOrderScheduleLineTypeCreate
    /// </summary>
    [DataContract(Name = "com.sap.gateway.srvd_a2x.api_purchaseorder_2.v0001.PurchaseOrderScheduleLine_Type-create")]
    public partial class PurchaseOrderPurchaseOrderScheduleLineTypeCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseOrderPurchaseOrderScheduleLineTypeCreate" /> class.
        /// </summary>
        [JsonConstructor]
        protected PurchaseOrderPurchaseOrderScheduleLineTypeCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PurchaseOrderPurchaseOrderScheduleLineTypeCreate" /> class.
        /// </summary>
        /// <param name="purchaseOrder">Purchasing Document Number (required).</param>
        /// <param name="purchaseOrderItem">Item Number of Purchasing Document (required).</param>
        /// <param name="scheduleLine">Delivery Schedule Line Counter (required).</param>
        /// <param name="scheduleLineDeliveryDate">Item Delivery Date.</param>
        /// <param name="schedLineStscDeliveryDate">Statistics-Relevant Delivery Date.</param>
        /// <param name="performancePeriodStartDate">Start Date for Period of Performance.</param>
        /// <param name="performancePeriodEndDate">End Date for Period of Performance.</param>
        /// <param name="scheduleLineDeliveryTime">Delivery Date Time-Spot.</param>
        /// <param name="batch">Batch Number.</param>
        /// <param name="batchBySupplier">Supplier Batch Number.</param>
        /// <param name="scheduleLineOrderQuantity">scheduleLineOrderQuantity.</param>
        /// <param name="openPurchaseOrderQuantity">openPurchaseOrderQuantity.</param>
        /// <param name="currency">Currency Key.</param>
        /// <param name="purchaseRequisition">Purchase Requisition Number.</param>
        /// <param name="purchaseRequisitionItem">Item Number of Purchase Requisition.</param>
        /// <param name="delivDateCategory">Category of delivery date.</param>
        /// <param name="scheduleLineOrderDate">Order date of schedule line.</param>
        /// <param name="productAvailabilityDate">Material Staging/Availability Date.</param>
        /// <param name="loadingDate">loadingDate.</param>
        /// <param name="loadingTime">Loading Time (Local Time Relating to a Shipping Point).</param>
        /// <param name="transportationPlanningDate">Transportation Planning Date.</param>
        /// <param name="transportationPlanningTime">Transp. Planning Time (Local, Relating to a Shipping Point).</param>
        /// <param name="goodsIssueDate">goodsIssueDate.</param>
        /// <param name="goodsIssueTime">Time of Goods Issue (Local, Relating to a Plant).</param>
        /// <param name="routeSchedule">routeSchedule.</param>
        /// <param name="productAvailabilityTime">Material Staging Time (Local, Relating to a Plant).</param>
        /// <param name="sAPMessages">sAPMessages.</param>
        /// <param name="purchaseOrder">purchaseOrder.</param>
        /// <param name="purchaseOrderItem">purchaseOrderItem.</param>
        /// <param name="subcontractingComponent">subcontractingComponent.</param>
        public PurchaseOrderPurchaseOrderScheduleLineTypeCreate(
            string purchaseOrder = default(string), string purchaseOrderItem = default(string),
            string scheduleLine = default(string), DateOnly? scheduleLineDeliveryDate = null,
            DateOnly? schedLineStscDeliveryDate = null,
            DateOnly? performancePeriodStartDate = null,
            DateOnly? performancePeriodEndDate = null, string scheduleLineDeliveryTime = default(string),
            string batch = default(string), string batchBySupplier = default(string),
            decimal scheduleLineOrderQuantity = default(decimal),
            PurchaseOrderPurchaseOrderScheduleLineTypeOpenPurchaseOrderQuantity
                openPurchaseOrderQuantity =
                default(
                    PurchaseOrderPurchaseOrderScheduleLineTypeOpenPurchaseOrderQuantity),
            string currency = default(string), string purchaseRequisition = default(string),
            string purchaseRequisitionItem = default(string), string delivDateCategory = default(string),
            DateOnly? scheduleLineOrderDate = null, DateOnly? productAvailabilityDate = null,
            DateOnly? loadingDate = null, string loadingTime = default(string),
            DateOnly? transportationPlanningDate = null,
            string transportationPlanningTime = default(string), DateOnly? goodsIssueDate = null,
            string goodsIssueTime = default(string), string routeSchedule = default(string),
            string productAvailabilityTime = default(string),
            List<PurchaseOrderSAPMessageCreate> sAPMessages =
                default(List<PurchaseOrderSAPMessageCreate>),
            PurchaseOrderPurchaseOrderTypeCreate _purchaseOrder =
                default(PurchaseOrderPurchaseOrderTypeCreate),
            PurchaseOrderPurchaseOrderItemTypeCreate _purchaseOrderItem =
                default(PurchaseOrderPurchaseOrderItemTypeCreate),
            List<PurchaseOrderPOSubcontractingComponentTypeCreate>
                _subcontractingComponent =
                default(List<PurchaseOrderPOSubcontractingComponentTypeCreate>))
        {
            // to ensure "purchaseOrder" is required (not null)
            if (purchaseOrder == null)
            {
                throw new ArgumentNullException("purchaseOrder is a required property for PurchaseOrderPurchaseOrderScheduleLineTypeCreate and cannot be null");
            }
            this.PurchaseOrder = purchaseOrder;
            // to ensure "purchaseOrderItem" is required (not null)
            if (purchaseOrderItem == null)
            {
                throw new ArgumentNullException("purchaseOrderItem is a required property for PurchaseOrderPurchaseOrderScheduleLineTypeCreate and cannot be null");
            }
            this.PurchaseOrderItem = purchaseOrderItem;
            // to ensure "scheduleLine" is required (not null)
            if (scheduleLine == null)
            {
                throw new ArgumentNullException("scheduleLine is a required property for PurchaseOrderPurchaseOrderScheduleLineTypeCreate and cannot be null");
            }
            this.ScheduleLine = scheduleLine;
            this.ScheduleLineDeliveryDate = scheduleLineDeliveryDate;
            this.SchedLineStscDeliveryDate = schedLineStscDeliveryDate;
            this.PerformancePeriodStartDate = performancePeriodStartDate;
            this.PerformancePeriodEndDate = performancePeriodEndDate;
            this.ScheduleLineDeliveryTime = scheduleLineDeliveryTime;
            this.Batch = batch;
            this.BatchBySupplier = batchBySupplier;
            this.ScheduleLineOrderQuantity = scheduleLineOrderQuantity;
            this.OpenPurchaseOrderQuantity = openPurchaseOrderQuantity;
            this.Currency = currency;
            this.PurchaseRequisition = purchaseRequisition;
            this.PurchaseRequisitionItem = purchaseRequisitionItem;
            this.DelivDateCategory = delivDateCategory;
            this.ScheduleLineOrderDate = scheduleLineOrderDate;
            this.ProductAvailabilityDate = productAvailabilityDate;
            this.LoadingDate = loadingDate;
            this.LoadingTime = loadingTime;
            this.TransportationPlanningDate = transportationPlanningDate;
            this.TransportationPlanningTime = transportationPlanningTime;
            this.GoodsIssueDate = goodsIssueDate;
            this.GoodsIssueTime = goodsIssueTime;
            this.RouteSchedule = routeSchedule;
            this.ProductAvailabilityTime = productAvailabilityTime;
            this.SAPMessages = sAPMessages;
            this._PurchaseOrder = _purchaseOrder;
            this._PurchaseOrderItem = _purchaseOrderItem;
            this._SubcontractingComponent = _subcontractingComponent;
        }

        /// <summary>
        /// Purchasing Document Number
        /// </summary>
        /// <value>Purchasing Document Number</value>
        [DataMember(Name = "PurchaseOrder", IsRequired = true, EmitDefaultValue = true)]
        public string PurchaseOrder { get; set; }

        /// <summary>
        /// Item Number of Purchasing Document
        /// </summary>
        /// <value>Item Number of Purchasing Document</value>
        [DataMember(Name = "PurchaseOrderItem", IsRequired = true, EmitDefaultValue = true)]
        public string PurchaseOrderItem { get; set; }

        /// <summary>
        /// Delivery Schedule Line Counter
        /// </summary>
        /// <value>Delivery Schedule Line Counter</value>
        [DataMember(Name = "ScheduleLine", IsRequired = true, EmitDefaultValue = true)]
        public string ScheduleLine { get; set; }

        /// <summary>
        /// Item Delivery Date
        /// </summary>
        /// <value>Item Delivery Date</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "ScheduleLineDeliveryDate", EmitDefaultValue = true)]
        public DateOnly? ScheduleLineDeliveryDate { get; set; }

        /// <summary>
        /// Statistics-Relevant Delivery Date
        /// </summary>
        /// <value>Statistics-Relevant Delivery Date</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "SchedLineStscDeliveryDate", EmitDefaultValue = true)]
        public DateOnly? SchedLineStscDeliveryDate { get; set; }

        /// <summary>
        /// Start Date for Period of Performance
        /// </summary>
        /// <value>Start Date for Period of Performance</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "PerformancePeriodStartDate", EmitDefaultValue = true)]
        public DateOnly? PerformancePeriodStartDate { get; set; }

        /// <summary>
        /// End Date for Period of Performance
        /// </summary>
        /// <value>End Date for Period of Performance</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "PerformancePeriodEndDate", EmitDefaultValue = true)]
        public DateOnly? PerformancePeriodEndDate { get; set; }

        /// <summary>
        /// Delivery Date Time-Spot
        /// </summary>
        /// <value>Delivery Date Time-Spot</value>
        /// <example>15:51:04</example>
        [DataMember(Name = "ScheduleLineDeliveryTime", EmitDefaultValue = false)]
        public string ScheduleLineDeliveryTime { get; set; }

        /// <summary>
        /// Batch Number
        /// </summary>
        /// <value>Batch Number</value>
        [DataMember(Name = "Batch", EmitDefaultValue = false)]
        public string Batch { get; set; }

        /// <summary>
        /// Supplier Batch Number
        /// </summary>
        /// <value>Supplier Batch Number</value>
        [DataMember(Name = "BatchBySupplier", EmitDefaultValue = false)]
        public string BatchBySupplier { get; set; }

        /// <summary>
        /// Gets or Sets ScheduleLineOrderQuantity
        /// </summary>
        [DataMember(Name = "ScheduleLineOrderQuantity", EmitDefaultValue = false)]
        public decimal ScheduleLineOrderQuantity { get; set; }

        /// <summary>
        /// Gets or Sets OpenPurchaseOrderQuantity
        /// </summary>
        [DataMember(Name = "OpenPurchaseOrderQuantity", EmitDefaultValue = false)]
        public PurchaseOrderPurchaseOrderScheduleLineTypeOpenPurchaseOrderQuantity OpenPurchaseOrderQuantity { get; set; }

        /// <summary>
        /// Currency Key
        /// </summary>
        /// <value>Currency Key</value>
        [DataMember(Name = "Currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Purchase Requisition Number
        /// </summary>
        /// <value>Purchase Requisition Number</value>
        [DataMember(Name = "PurchaseRequisition", EmitDefaultValue = false)]
        public string PurchaseRequisition { get; set; }

        /// <summary>
        /// Item Number of Purchase Requisition
        /// </summary>
        /// <value>Item Number of Purchase Requisition</value>
        [DataMember(Name = "PurchaseRequisitionItem", EmitDefaultValue = false)]
        public string PurchaseRequisitionItem { get; set; }

        /// <summary>
        /// Category of delivery date
        /// </summary>
        /// <value>Category of delivery date</value>
        [DataMember(Name = "DelivDateCategory", EmitDefaultValue = false)]
        public string DelivDateCategory { get; set; }

        /// <summary>
        /// Order date of schedule line
        /// </summary>
        /// <value>Order date of schedule line</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "ScheduleLineOrderDate", EmitDefaultValue = true)]
        public DateOnly? ScheduleLineOrderDate { get; set; }

        /// <summary>
        /// Material Staging/Availability Date
        /// </summary>
        /// <value>Material Staging/Availability Date</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "ProductAvailabilityDate", EmitDefaultValue = true)]
        public DateOnly? ProductAvailabilityDate { get; set; }

        /// <summary>
        /// Gets or Sets LoadingDate
        /// </summary>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "LoadingDate", EmitDefaultValue = true)]
        public DateOnly? LoadingDate { get; set; }

        /// <summary>
        /// Loading Time (Local Time Relating to a Shipping Point)
        /// </summary>
        /// <value>Loading Time (Local Time Relating to a Shipping Point)</value>
        /// <example>15:51:04</example>
        [DataMember(Name = "LoadingTime", EmitDefaultValue = false)]
        public string LoadingTime { get; set; }

        /// <summary>
        /// Transportation Planning Date
        /// </summary>
        /// <value>Transportation Planning Date</value>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "TransportationPlanningDate", EmitDefaultValue = true)]
        public DateOnly? TransportationPlanningDate { get; set; }

        /// <summary>
        /// Transp. Planning Time (Local, Relating to a Shipping Point)
        /// </summary>
        /// <value>Transp. Planning Time (Local, Relating to a Shipping Point)</value>
        /// <example>15:51:04</example>
        [DataMember(Name = "TransportationPlanningTime", EmitDefaultValue = false)]
        public string TransportationPlanningTime { get; set; }

        /// <summary>
        /// Gets or Sets GoodsIssueDate
        /// </summary>
        /// <example>Thu Apr 13 08:00:00 AWST 2017</example>
        [DataMember(Name = "GoodsIssueDate", EmitDefaultValue = true)]
        public DateOnly? GoodsIssueDate { get; set; }

        /// <summary>
        /// Time of Goods Issue (Local, Relating to a Plant)
        /// </summary>
        /// <value>Time of Goods Issue (Local, Relating to a Plant)</value>
        /// <example>15:51:04</example>
        [DataMember(Name = "GoodsIssueTime", EmitDefaultValue = false)]
        public string GoodsIssueTime { get; set; }

        /// <summary>
        /// Gets or Sets RouteSchedule
        /// </summary>
        [DataMember(Name = "RouteSchedule", EmitDefaultValue = false)]
        public string RouteSchedule { get; set; }

        /// <summary>
        /// Material Staging Time (Local, Relating to a Plant)
        /// </summary>
        /// <value>Material Staging Time (Local, Relating to a Plant)</value>
        /// <example>15:51:04</example>
        [DataMember(Name = "ProductAvailabilityTime", EmitDefaultValue = false)]
        public string ProductAvailabilityTime { get; set; }

        /// <summary>
        /// Gets or Sets SAPMessages
        /// </summary>
        [DataMember(Name = "SAP__Messages", EmitDefaultValue = false)]
        public List<PurchaseOrderSAPMessageCreate> SAPMessages { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseOrder
        /// </summary>
        [DataMember(Name = "_PurchaseOrder", EmitDefaultValue = false)]
        public PurchaseOrderPurchaseOrderTypeCreate _PurchaseOrder { get; set; }

        /// <summary>
        /// Gets or Sets PurchaseOrderItem
        /// </summary>
        [DataMember(Name = "_PurchaseOrderItem", EmitDefaultValue = false)]
        public PurchaseOrderPurchaseOrderItemTypeCreate _PurchaseOrderItem { get; set; }

        /// <summary>
        /// Gets or Sets SubcontractingComponent
        /// </summary>
        [DataMember(Name = "_SubcontractingComponent", EmitDefaultValue = false)]
        public List<PurchaseOrderPOSubcontractingComponentTypeCreate> _SubcontractingComponent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PurchaseOrderPurchaseOrderScheduleLineTypeCreate {\n");
            sb.Append("  PurchaseOrder: ").Append(PurchaseOrder).Append("\n");
            sb.Append("  PurchaseOrderItem: ").Append(PurchaseOrderItem).Append("\n");
            sb.Append("  ScheduleLine: ").Append(ScheduleLine).Append("\n");
            sb.Append("  ScheduleLineDeliveryDate: ").Append(ScheduleLineDeliveryDate).Append("\n");
            sb.Append("  SchedLineStscDeliveryDate: ").Append(SchedLineStscDeliveryDate).Append("\n");
            sb.Append("  PerformancePeriodStartDate: ").Append(PerformancePeriodStartDate).Append("\n");
            sb.Append("  PerformancePeriodEndDate: ").Append(PerformancePeriodEndDate).Append("\n");
            sb.Append("  ScheduleLineDeliveryTime: ").Append(ScheduleLineDeliveryTime).Append("\n");
            sb.Append("  Batch: ").Append(Batch).Append("\n");
            sb.Append("  BatchBySupplier: ").Append(BatchBySupplier).Append("\n");
            sb.Append("  ScheduleLineOrderQuantity: ").Append(ScheduleLineOrderQuantity).Append("\n");
            sb.Append("  OpenPurchaseOrderQuantity: ").Append(OpenPurchaseOrderQuantity).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  PurchaseRequisition: ").Append(PurchaseRequisition).Append("\n");
            sb.Append("  PurchaseRequisitionItem: ").Append(PurchaseRequisitionItem).Append("\n");
            sb.Append("  DelivDateCategory: ").Append(DelivDateCategory).Append("\n");
            sb.Append("  ScheduleLineOrderDate: ").Append(ScheduleLineOrderDate).Append("\n");
            sb.Append("  ProductAvailabilityDate: ").Append(ProductAvailabilityDate).Append("\n");
            sb.Append("  LoadingDate: ").Append(LoadingDate).Append("\n");
            sb.Append("  LoadingTime: ").Append(LoadingTime).Append("\n");
            sb.Append("  TransportationPlanningDate: ").Append(TransportationPlanningDate).Append("\n");
            sb.Append("  TransportationPlanningTime: ").Append(TransportationPlanningTime).Append("\n");
            sb.Append("  GoodsIssueDate: ").Append(GoodsIssueDate).Append("\n");
            sb.Append("  GoodsIssueTime: ").Append(GoodsIssueTime).Append("\n");
            sb.Append("  RouteSchedule: ").Append(RouteSchedule).Append("\n");
            sb.Append("  ProductAvailabilityTime: ").Append(ProductAvailabilityTime).Append("\n");
            sb.Append("  SAPMessages: ").Append(SAPMessages).Append("\n");
            sb.Append("  PurchaseOrder: ").Append(PurchaseOrder).Append("\n");
            sb.Append("  PurchaseOrderItem: ").Append(PurchaseOrderItem).Append("\n");
            sb.Append("  SubcontractingComponent: ").Append(_SubcontractingComponent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PurchaseOrder (string) maxLength
            if (this.PurchaseOrder != null && this.PurchaseOrder.Length > 10)
            {
                yield return new ValidationResult("Invalid value for PurchaseOrder, length must be less than 10.", new [] { "PurchaseOrder" });
            }

            // PurchaseOrderItem (string) maxLength
            if (this.PurchaseOrderItem != null && this.PurchaseOrderItem.Length > 5)
            {
                yield return new ValidationResult("Invalid value for PurchaseOrderItem, length must be less than 5.", new [] { "PurchaseOrderItem" });
            }

            // ScheduleLine (string) maxLength
            if (this.ScheduleLine != null && this.ScheduleLine.Length > 4)
            {
                yield return new ValidationResult("Invalid value for ScheduleLine, length must be less than 4.", new [] { "ScheduleLine" });
            }

            // Batch (string) maxLength
            if (this.Batch != null && this.Batch.Length > 10)
            {
                yield return new ValidationResult("Invalid value for Batch, length must be less than 10.", new [] { "Batch" });
            }

            // BatchBySupplier (string) maxLength
            if (this.BatchBySupplier != null && this.BatchBySupplier.Length > 15)
            {
                yield return new ValidationResult("Invalid value for BatchBySupplier, length must be less than 15.", new [] { "BatchBySupplier" });
            }

            // Currency (string) maxLength
            if (this.Currency != null && this.Currency.Length > 3)
            {
                yield return new ValidationResult("Invalid value for Currency, length must be less than 3.", new [] { "Currency" });
            }

            // PurchaseRequisition (string) maxLength
            if (this.PurchaseRequisition != null && this.PurchaseRequisition.Length > 10)
            {
                yield return new ValidationResult("Invalid value for PurchaseRequisition, length must be less than 10.", new [] { "PurchaseRequisition" });
            }

            // PurchaseRequisitionItem (string) maxLength
            if (this.PurchaseRequisitionItem != null && this.PurchaseRequisitionItem.Length > 5)
            {
                yield return new ValidationResult("Invalid value for PurchaseRequisitionItem, length must be less than 5.", new [] { "PurchaseRequisitionItem" });
            }

            // DelivDateCategory (string) maxLength
            if (this.DelivDateCategory != null && this.DelivDateCategory.Length > 1)
            {
                yield return new ValidationResult("Invalid value for DelivDateCategory, length must be less than 1.", new [] { "DelivDateCategory" });
            }

            // RouteSchedule (string) maxLength
            if (this.RouteSchedule != null && this.RouteSchedule.Length > 10)
            {
                yield return new ValidationResult("Invalid value for RouteSchedule, length must be less than 10.", new [] { "RouteSchedule" });
            }

            yield break;
        }
    }

}
