/*
 * Purchase Order
 *
 * This service enables you to create purchase orders through an API call from a source system outside SAP S/4HANA Cloud. Furthermore, the service enables you to read, update or delete existing purchase orders from the SAP S/4HANA Cloud system. The service is based on the OData protocol.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace Sap.Model.PurchaseOrder
{
    /// <summary>
    /// PurchaseOrderPurchaseOrderPartnerTypeUpdate
    /// </summary>
    [DataContract(Name = "com.sap.gateway.srvd_a2x.api_purchaseorder_2.v0001.PurchaseOrderPartner_Type-update")]
    public partial class PurchaseOrderPurchaseOrderPartnerTypeUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref = "PurchaseOrderPurchaseOrderPartnerTypeUpdate"/> class.
        /// </summary>
        /// <param name = "purchasingDocumentPartnerType">Type of partner number.</param>
        /// <param name = "supplier">Account Number of Supplier.</param>
        /// <param name = "supplierHierarchyCategory">Hierarchy Category: Supplier Hierarchy.</param>
        /// <param name = "supplierContact">Number of Contact EhsPersonWrapper.</param>
        /// <param name = "personWorkAgreement">personWorkAgreement.</param>
        /// <param name = "employmentInternalID">employmentInternalID.</param>
        public PurchaseOrderPurchaseOrderPartnerTypeUpdate(string purchasingDocumentPartnerType = default(string), string supplier = default(string), string supplierHierarchyCategory = default(string), string supplierContact = default(string), string personWorkAgreement = default(string), string employmentInternalID = default(string))
        {
            this.PurchasingDocumentPartnerType = purchasingDocumentPartnerType;
            this.Supplier = supplier;
            this.SupplierHierarchyCategory = supplierHierarchyCategory;
            this.SupplierContact = supplierContact;
            this.PersonWorkAgreement = personWorkAgreement;
            this.EmploymentInternalID = employmentInternalID;
        }

        /// <summary>
        /// Type of partner number
        /// </summary>
        /// <value>Type of partner number</value>
        [DataMember(Name = "PurchasingDocumentPartnerType", EmitDefaultValue = false)]
        public string PurchasingDocumentPartnerType { get; set; }

        /// <summary>
        /// Account Number of Supplier
        /// </summary>
        /// <value>Account Number of Supplier</value>
        [DataMember(Name = "Supplier", EmitDefaultValue = false)]
        public string Supplier { get; set; }

        /// <summary>
        /// Hierarchy Category: Supplier Hierarchy
        /// </summary>
        /// <value>Hierarchy Category: Supplier Hierarchy</value>
        [DataMember(Name = "SupplierHierarchyCategory", EmitDefaultValue = false)]
        public string SupplierHierarchyCategory { get; set; }

        /// <summary>
        /// Number of Contact EhsPersonWrapper
        /// </summary>
        /// <value>Number of Contact EhsPersonWrapper</value>
        [DataMember(Name = "SupplierContact", EmitDefaultValue = false)]
        public string SupplierContact { get; set; }

        /// <summary>
        /// Gets or Sets PersonWorkAgreement
        /// </summary>
        [DataMember(Name = "PersonWorkAgreement", EmitDefaultValue = false)]
        public string PersonWorkAgreement { get; set; }

        /// <summary>
        /// Gets or Sets EmploymentInternalID
        /// </summary>
        [DataMember(Name = "EmploymentInternalID", EmitDefaultValue = false)]
        public string EmploymentInternalID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PurchaseOrderPurchaseOrderPartnerTypeUpdate {\n");
            sb.Append("  PurchasingDocumentPartnerType: ").Append(PurchasingDocumentPartnerType).Append("\n");
            sb.Append("  Supplier: ").Append(Supplier).Append("\n");
            sb.Append("  SupplierHierarchyCategory: ").Append(SupplierHierarchyCategory).Append("\n");
            sb.Append("  SupplierContact: ").Append(SupplierContact).Append("\n");
            sb.Append("  PersonWorkAgreement: ").Append(PersonWorkAgreement).Append("\n");
            sb.Append("  EmploymentInternalID: ").Append(EmploymentInternalID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name = "validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // PurchasingDocumentPartnerType (string) maxLength
            if (this.PurchasingDocumentPartnerType != null && this.PurchasingDocumentPartnerType.Length > 2)
            {
                yield return new ValidationResult("Invalid value for PurchasingDocumentPartnerType, length must be less than 2.", new[] { "PurchasingDocumentPartnerType" });
            }

            // Supplier (string) maxLength
            if (this.Supplier != null && this.Supplier.Length > 10)
            {
                yield return new ValidationResult("Invalid value for Supplier, length must be less than 10.", new[] { "Supplier" });
            }

            // SupplierHierarchyCategory (string) maxLength
            if (this.SupplierHierarchyCategory != null && this.SupplierHierarchyCategory.Length > 1)
            {
                yield return new ValidationResult("Invalid value for SupplierHierarchyCategory, length must be less than 1.", new[] { "SupplierHierarchyCategory" });
            }

            // SupplierContact (string) maxLength
            if (this.SupplierContact != null && this.SupplierContact.Length > 10)
            {
                yield return new ValidationResult("Invalid value for SupplierContact, length must be less than 10.", new[] { "SupplierContact" });
            }

            // PersonWorkAgreement (string) maxLength
            if (this.PersonWorkAgreement != null && this.PersonWorkAgreement.Length > 8)
            {
                yield return new ValidationResult("Invalid value for PersonWorkAgreement, length must be less than 8.", new[] { "PersonWorkAgreement" });
            }

            // EmploymentInternalID (string) maxLength
            if (this.EmploymentInternalID != null && this.EmploymentInternalID.Length > 8)
            {
                yield return new ValidationResult("Invalid value for EmploymentInternalID, length must be less than 8.", new[] { "EmploymentInternalID" });
            }

            yield break;
        }

        public PurchaseOrderPurchaseOrderPartnerTypeUpdate()
        {
        }
    }
}
